[2023-06-26T18:52:06.210+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: dbt_ipflow_dag.get_input_data manual__2023-06-26T18:52:04.674534+00:00 [queued]>
[2023-06-26T18:52:06.220+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: dbt_ipflow_dag.get_input_data manual__2023-06-26T18:52:04.674534+00:00 [queued]>
[2023-06-26T18:52:06.222+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-06-26T18:52:06.223+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2023-06-26T18:52:06.224+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-06-26T18:52:06.238+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): get_input_data> on 2023-06-26 18:52:04.674534+00:00
[2023-06-26T18:52:06.247+0000] {standard_task_runner.py:55} INFO - Started process 26764 to run task
[2023-06-26T18:52:06.263+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dbt_ipflow_dag', 'get_input_data', 'manual__2023-06-26T18:52:04.674534+00:00', '--job-id', '63', '--raw', '--subdir', 'DAGS_FOLDER/dbt_ip_flow_dag.py', '--cfg-path', '/tmp/tmpvedwd4x0']
[2023-06-26T18:52:06.279+0000] {standard_task_runner.py:83} INFO - Job 63: Subtask get_input_data
[2023-06-26T18:52:06.358+0000] {task_command.py:389} INFO - Running <TaskInstance: dbt_ipflow_dag.get_input_data manual__2023-06-26T18:52:04.674534+00:00 [running]> on host 635f1a4ac995
[2023-06-26T18:52:06.421+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dbt_ipflow_dag
AIRFLOW_CTX_TASK_ID=get_input_data
AIRFLOW_CTX_EXECUTION_DATE=2023-06-26T18:52:04.674534+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-06-26T18:52:04.674534+00:00
[2023-06-26T18:52:06.424+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-06-26T18:52:06.430+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', "dbt run --select stg_ipflow_input_data --profiles-dir /opt/***/dbt/dbt_dsg_app --project-dir /opt/***/dbt/dbt_dsg_app  --target DEV --vars {'env': 'DEV'} "]
[2023-06-26T18:52:06.448+0000] {subprocess.py:86} INFO - Output:
[2023-06-26T18:52:07.807+0000] {subprocess.py:93} INFO - [0m18:52:07  The YAML provided in the --vars argument is not valid.
[2023-06-26T18:52:07.824+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-06-26T18:52:07.825+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/dbt/clients/yaml_helper.py", line 56, in load_yaml_text
[2023-06-26T18:52:07.826+0000] {subprocess.py:93} INFO -     return safe_load(contents)
[2023-06-26T18:52:07.828+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/dbt/clients/yaml_helper.py", line 51, in safe_load
[2023-06-26T18:52:07.829+0000] {subprocess.py:93} INFO -     return yaml.load(contents, Loader=SafeLoader)
[2023-06-26T18:52:07.830+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/yaml/__init__.py", line 81, in load
[2023-06-26T18:52:07.831+0000] {subprocess.py:93} INFO -     return loader.get_single_data()
[2023-06-26T18:52:07.832+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/yaml/constructor.py", line 49, in get_single_data
[2023-06-26T18:52:07.833+0000] {subprocess.py:93} INFO -     node = self.get_single_node()
[2023-06-26T18:52:07.838+0000] {subprocess.py:93} INFO -   File "yaml/_yaml.pyx", line 673, in yaml._yaml.CParser.get_single_node
[2023-06-26T18:52:07.839+0000] {subprocess.py:93} INFO -   File "yaml/_yaml.pyx", line 687, in yaml._yaml.CParser._compose_document
[2023-06-26T18:52:07.841+0000] {subprocess.py:93} INFO -   File "yaml/_yaml.pyx", line 731, in yaml._yaml.CParser._compose_node
[2023-06-26T18:52:07.843+0000] {subprocess.py:93} INFO -   File "yaml/_yaml.pyx", line 845, in yaml._yaml.CParser._compose_mapping_node
[2023-06-26T18:52:07.845+0000] {subprocess.py:93} INFO -   File "yaml/_yaml.pyx", line 694, in yaml._yaml.CParser._compose_node
[2023-06-26T18:52:07.847+0000] {subprocess.py:93} INFO -   File "yaml/_yaml.pyx", line 860, in yaml._yaml.CParser._parse_next_event
[2023-06-26T18:52:07.848+0000] {subprocess.py:93} INFO - yaml.parser.ParserError: while parsing a flow node
[2023-06-26T18:52:07.849+0000] {subprocess.py:93} INFO - did not find expected node content
[2023-06-26T18:52:07.850+0000] {subprocess.py:93} INFO -   in "<unicode string>", line 2, column 1
[2023-06-26T18:52:07.852+0000] {subprocess.py:93} INFO - 
[2023-06-26T18:52:07.852+0000] {subprocess.py:93} INFO - During handling of the above exception, another exception occurred:
[2023-06-26T18:52:07.853+0000] {subprocess.py:93} INFO - 
[2023-06-26T18:52:07.854+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-06-26T18:52:07.855+0000] {subprocess.py:93} INFO -   File "/home/***/.local/bin/dbt", line 8, in <module>
[2023-06-26T18:52:07.856+0000] {subprocess.py:93} INFO -     sys.exit(cli())
[2023-06-26T18:52:07.857+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/click/core.py", line 1130, in __call__
[2023-06-26T18:52:07.858+0000] {subprocess.py:93} INFO -     return self.main(*args, **kwargs)
[2023-06-26T18:52:07.859+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/click/core.py", line 1055, in main
[2023-06-26T18:52:07.860+0000] {subprocess.py:93} INFO -     rv = self.invoke(ctx)
[2023-06-26T18:52:07.862+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/click/core.py", line 1655, in invoke
[2023-06-26T18:52:07.863+0000] {subprocess.py:93} INFO -     sub_ctx = cmd.make_context(cmd_name, args, parent=ctx)
[2023-06-26T18:52:07.864+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/click/core.py", line 920, in make_context
[2023-06-26T18:52:07.864+0000] {subprocess.py:93} INFO -     self.parse_args(ctx, args)
[2023-06-26T18:52:07.865+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/click/core.py", line 1378, in parse_args
[2023-06-26T18:52:07.866+0000] {subprocess.py:93} INFO -     value, args = param.handle_parse_result(ctx, opts, args)
[2023-06-26T18:52:07.867+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/click/core.py", line 2360, in handle_parse_result
[2023-06-26T18:52:07.868+0000] {subprocess.py:93} INFO -     value = self.process_value(ctx, value)
[2023-06-26T18:52:07.869+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/click/core.py", line 2316, in process_value
[2023-06-26T18:52:07.870+0000] {subprocess.py:93} INFO -     value = self.type_cast_value(ctx, value)
[2023-06-26T18:52:07.895+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/click/core.py", line 2304, in type_cast_value
[2023-06-26T18:52:07.896+0000] {subprocess.py:93} INFO -     return convert(value)
[2023-06-26T18:52:07.898+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/click/types.py", line 82, in __call__
[2023-06-26T18:52:07.899+0000] {subprocess.py:93} INFO -     return self.convert(value, param, ctx)
[2023-06-26T18:52:07.903+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/dbt/cli/option_types.py", line 19, in convert
[2023-06-26T18:52:07.904+0000] {subprocess.py:93} INFO -     return parse_cli_vars(value)
[2023-06-26T18:52:07.905+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/dbt/config/utils.py", line 11, in parse_cli_vars
[2023-06-26T18:52:07.906+0000] {subprocess.py:93} INFO -     return parse_cli_yaml_string(var_string, "vars")
[2023-06-26T18:52:07.907+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/dbt/config/utils.py", line 16, in parse_cli_yaml_string
[2023-06-26T18:52:07.908+0000] {subprocess.py:93} INFO -     cli_vars = yaml_helper.load_yaml_text(var_string)
[2023-06-26T18:52:07.909+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/dbt/clients/yaml_helper.py", line 63, in load_yaml_text
[2023-06-26T18:52:07.912+0000] {subprocess.py:93} INFO -     raise dbt.exceptions.DbtValidationError(error)
[2023-06-26T18:52:07.913+0000] {subprocess.py:93} INFO - dbt.exceptions.DbtValidationError: Runtime Error
[2023-06-26T18:52:07.914+0000] {subprocess.py:93} INFO -   Syntax error near line 2
[2023-06-26T18:52:07.918+0000] {subprocess.py:93} INFO -   ------------------------------
[2023-06-26T18:52:07.920+0000] {subprocess.py:93} INFO -   1  | {env:
[2023-06-26T18:52:07.921+0000] {subprocess.py:93} INFO - 
[2023-06-26T18:52:07.922+0000] {subprocess.py:93} INFO -   Raw Error:
[2023-06-26T18:52:07.923+0000] {subprocess.py:93} INFO -   ------------------------------
[2023-06-26T18:52:07.924+0000] {subprocess.py:93} INFO -   while parsing a flow node
[2023-06-26T18:52:07.925+0000] {subprocess.py:93} INFO -   did not find expected node content
[2023-06-26T18:52:07.927+0000] {subprocess.py:93} INFO -     in "<unicode string>", line 2, column 1
[2023-06-26T18:52:07.954+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-06-26T18:52:07.979+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-06-26T18:52:07.984+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=dbt_ipflow_dag, task_id=get_input_data, execution_date=20230626T185204, start_date=20230626T185206, end_date=20230626T185207
[2023-06-26T18:52:07.997+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 63 for task get_input_data (Bash command failed. The command returned a non-zero exit code 1.; 26764)
[2023-06-26T18:52:08.037+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-06-26T18:52:08.063+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
