[2023-08-03T00:00:01.836+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: dbt_ipflow_dag.get_input_data scheduled__2023-08-02T00:00:00+00:00 [queued]>
[2023-08-03T00:00:01.843+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: dbt_ipflow_dag.get_input_data scheduled__2023-08-02T00:00:00+00:00 [queued]>
[2023-08-03T00:00:01.844+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-08-03T00:00:01.846+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2023-08-03T00:00:01.847+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-08-03T00:00:01.856+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): get_input_data> on 2023-08-02 00:00:00+00:00
[2023-08-03T00:00:01.862+0000] {standard_task_runner.py:55} INFO - Started process 4591 to run task
[2023-08-03T00:00:01.867+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dbt_ipflow_dag', 'get_input_data', 'scheduled__2023-08-02T00:00:00+00:00', '--job-id', '99', '--raw', '--subdir', 'DAGS_FOLDER/dbt_ip_flow_dag.py', '--cfg-path', '/tmp/tmpmw1uz683']
[2023-08-03T00:00:01.871+0000] {standard_task_runner.py:83} INFO - Job 99: Subtask get_input_data
[2023-08-03T00:00:01.935+0000] {task_command.py:389} INFO - Running <TaskInstance: dbt_ipflow_dag.get_input_data scheduled__2023-08-02T00:00:00+00:00 [running]> on host 635f1a4ac995
[2023-08-03T00:00:01.995+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dbt_ipflow_dag
AIRFLOW_CTX_TASK_ID=get_input_data
AIRFLOW_CTX_EXECUTION_DATE=2023-08-02T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-08-02T00:00:00+00:00
[2023-08-03T00:00:01.998+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-08-03T00:00:02.000+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', "dbt run --select stg_ipflow_input_data --profiles-dir /opt/***/dbt/dbt_dsg_app --project-dir /opt/***/dbt/dbt_dsg_app  --target dev --vars '{'env': 'dev'}' "]
[2023-08-03T00:00:02.014+0000] {subprocess.py:86} INFO - Output:
[2023-08-03T00:00:03.414+0000] {subprocess.py:93} INFO - [0m00:00:03  Running with dbt=1.5.1
[2023-08-03T00:00:04.091+0000] {subprocess.py:93} INFO - [0m00:00:04  Found 12 models, 2 tests, 0 snapshots, 0 analyses, 321 macros, 0 operations, 0 seed files, 0 sources, 0 exposures, 0 metrics, 0 groups
[2023-08-03T00:00:04.097+0000] {subprocess.py:93} INFO - [0m00:00:04
[2023-08-03T00:00:04.989+0000] {subprocess.py:93} INFO - [0m00:00:04
[2023-08-03T00:00:04.991+0000] {subprocess.py:93} INFO - [0m00:00:04  Finished running  in 0 hours 0 minutes and 0.89 seconds (0.89s).
[2023-08-03T00:00:04.994+0000] {subprocess.py:93} INFO - [0m00:00:04  Encountered an error:
[2023-08-03T00:00:04.995+0000] {subprocess.py:93} INFO - Runtime Error
[2023-08-03T00:00:04.996+0000] {subprocess.py:93} INFO -   Database error while listing schemas in database "DEV_QA"
[2023-08-03T00:00:04.997+0000] {subprocess.py:93} INFO -   Database Error
[2023-08-03T00:00:04.998+0000] {subprocess.py:93} INFO -     250001 (08001): Failed to connect to DB: bcb55215.us-east-1.snowflakecomputing.com:443. Incorrect username or password was specified.
[2023-08-03T00:00:05.538+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-08-03T00:00:05.551+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-08-03T00:00:05.556+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=dbt_ipflow_dag, task_id=get_input_data, execution_date=20230802T000000, start_date=20230803T000001, end_date=20230803T000005
[2023-08-03T00:00:05.570+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 99 for task get_input_data (Bash command failed. The command returned a non-zero exit code 2.; 4591)
[2023-08-03T00:00:05.621+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-08-03T00:00:05.645+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
