[2023-07-24T02:26:53.205+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: dbt_ipflow_dag.get_input_data manual__2023-07-24T02:26:50.654432+00:00 [queued]>
[2023-07-24T02:26:53.218+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: dbt_ipflow_dag.get_input_data manual__2023-07-24T02:26:50.654432+00:00 [queued]>
[2023-07-24T02:26:53.227+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-07-24T02:26:53.228+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2023-07-24T02:26:53.229+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-07-24T02:26:53.239+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): get_input_data> on 2023-07-24 02:26:50.654432+00:00
[2023-07-24T02:26:53.251+0000] {standard_task_runner.py:55} INFO - Started process 38222 to run task
[2023-07-24T02:26:53.256+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dbt_ipflow_dag', 'get_input_data', 'manual__2023-07-24T02:26:50.654432+00:00', '--job-id', '78', '--raw', '--subdir', 'DAGS_FOLDER/dbt_ip_flow_dag.py', '--cfg-path', '/tmp/tmp04snpert']
[2023-07-24T02:26:53.260+0000] {standard_task_runner.py:83} INFO - Job 78: Subtask get_input_data
[2023-07-24T02:26:53.391+0000] {task_command.py:389} INFO - Running <TaskInstance: dbt_ipflow_dag.get_input_data manual__2023-07-24T02:26:50.654432+00:00 [running]> on host 635f1a4ac995
[2023-07-24T02:26:53.551+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dbt_ipflow_dag
AIRFLOW_CTX_TASK_ID=get_input_data
AIRFLOW_CTX_EXECUTION_DATE=2023-07-24T02:26:50.654432+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-07-24T02:26:50.654432+00:00
[2023-07-24T02:26:53.555+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-07-24T02:26:53.556+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', "dbt run --select stg_ipflow_input_data --profiles-dir /opt/***/dbt/dbt_dsg_app --project-dir /opt/***/dbt/dbt_dsg_app  --target dev --vars '{'env': 'dev'}' "]
[2023-07-24T02:26:53.589+0000] {subprocess.py:86} INFO - Output:
[2023-07-24T02:26:59.299+0000] {subprocess.py:93} INFO - [0m02:26:59  Running with dbt=1.5.1
[2023-07-24T02:27:01.313+0000] {subprocess.py:93} INFO - [0m02:27:01  Unable to do partial parsing because config vars, config profile, or config target have changed
[2023-07-24T02:27:02.773+0000] {subprocess.py:93} INFO - [0m02:27:02  Found 12 models, 2 tests, 0 snapshots, 0 analyses, 321 macros, 0 operations, 0 seed files, 0 sources, 0 exposures, 0 metrics, 0 groups
[2023-07-24T02:27:02.804+0000] {subprocess.py:93} INFO - [0m02:27:02
[2023-07-24T02:27:04.752+0000] {subprocess.py:93} INFO - [0m02:27:04  Concurrency: 4 threads (target='dev')
[2023-07-24T02:27:04.761+0000] {subprocess.py:93} INFO - [0m02:27:04
[2023-07-24T02:27:04.776+0000] {subprocess.py:93} INFO - [0m02:27:04  1 of 1 START sql table model DBT_POC.stg_ipflow_input_data ..................... [RUN]
[2023-07-24T02:27:05.558+0000] {subprocess.py:93} INFO - [0m02:27:05  1 of 1 ERROR creating sql table model DBT_POC.stg_ipflow_input_data ............ [[31mERROR[0m in 0.74s]
[2023-07-24T02:27:05.589+0000] {subprocess.py:93} INFO - [0m02:27:05
[2023-07-24T02:27:05.591+0000] {subprocess.py:93} INFO - [0m02:27:05  Finished running 1 table model in 0 hours 0 minutes and 2.78 seconds (2.78s).
[2023-07-24T02:27:05.629+0000] {subprocess.py:93} INFO - [0m02:27:05
[2023-07-24T02:27:05.632+0000] {subprocess.py:93} INFO - [0m02:27:05  [31mCompleted with 1 error and 0 warnings:[0m
[2023-07-24T02:27:05.636+0000] {subprocess.py:93} INFO - [0m02:27:05
[2023-07-24T02:27:05.638+0000] {subprocess.py:93} INFO - [0m02:27:05  [33mDatabase Error in model stg_ipflow_input_data (models/ipflow/stg_ipflow_input_data.sql)[0m
[2023-07-24T02:27:05.643+0000] {subprocess.py:93} INFO - [0m02:27:05    002003 (42S02): SQL compilation error:
[2023-07-24T02:27:05.694+0000] {subprocess.py:93} INFO - [0m02:27:05    Object 'FIVE_BY_FIVE_DEMO.PRODUCTS.IP_COMPANY_2_9_0' does not exist or not authorized.
[2023-07-24T02:27:05.698+0000] {subprocess.py:93} INFO - [0m02:27:05    compiled Code at target/run/dbt_dsg_app/models/ipflow/stg_ipflow_input_data.sql
[2023-07-24T02:27:05.703+0000] {subprocess.py:93} INFO - [0m02:27:05
[2023-07-24T02:27:05.706+0000] {subprocess.py:93} INFO - [0m02:27:05  Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1
[2023-07-24T02:27:06.367+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-07-24T02:27:06.394+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-07-24T02:27:06.402+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=dbt_ipflow_dag, task_id=get_input_data, execution_date=20230724T022650, start_date=20230724T022653, end_date=20230724T022706
[2023-07-24T02:27:06.431+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 78 for task get_input_data (Bash command failed. The command returned a non-zero exit code 1.; 38222)
[2023-07-24T02:27:06.494+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-07-24T02:27:06.525+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
