[2023-06-20T18:38:40.805+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: dbt_ipflow_dag.dbt_run scheduled__2023-06-19T00:00:00+00:00 [queued]>
[2023-06-20T18:38:40.813+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: dbt_ipflow_dag.dbt_run scheduled__2023-06-19T00:00:00+00:00 [queued]>
[2023-06-20T18:38:40.814+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-06-20T18:38:40.815+0000] {taskinstance.py:1284} INFO - Starting attempt 8 of 8
[2023-06-20T18:38:40.816+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-06-20T18:38:40.827+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): dbt_run> on 2023-06-19 00:00:00+00:00
[2023-06-20T18:38:40.835+0000] {standard_task_runner.py:55} INFO - Started process 4924 to run task
[2023-06-20T18:38:40.840+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dbt_ipflow_dag', 'dbt_run', 'scheduled__2023-06-19T00:00:00+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/dbt_ip_flow_dag.py', '--cfg-path', '/tmp/tmpwsfyx6_2']
[2023-06-20T18:38:40.843+0000] {standard_task_runner.py:83} INFO - Job 14: Subtask dbt_run
[2023-06-20T18:38:40.926+0000] {task_command.py:389} INFO - Running <TaskInstance: dbt_ipflow_dag.dbt_run scheduled__2023-06-19T00:00:00+00:00 [running]> on host 635f1a4ac995
[2023-06-20T18:38:40.990+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dbt_ipflow_dag
AIRFLOW_CTX_TASK_ID=dbt_run
AIRFLOW_CTX_EXECUTION_DATE=2023-06-19T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=8
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-06-19T00:00:00+00:00
[2023-06-20T18:38:40.993+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-06-20T18:38:40.994+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'source /opt/***/dbt_venv/bin/activate && dbt run --models .']
[2023-06-20T18:38:41.011+0000] {subprocess.py:86} INFO - Output:
[2023-06-20T18:38:41.035+0000] {subprocess.py:93} INFO - /bin/bash: line 1: dbt: command not found
[2023-06-20T18:38:41.037+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2023-06-20T18:38:41.056+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-06-20T18:38:41.061+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=dbt_ipflow_dag, task_id=dbt_run, execution_date=20230619T000000, start_date=20230620T183840, end_date=20230620T183841
[2023-06-20T18:38:41.086+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 14 for task dbt_run (Bash command failed. The command returned a non-zero exit code 127.; 4924)
[2023-06-20T18:38:41.132+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-06-20T18:38:41.152+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
