[2023-07-30T00:15:19.871+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: dbt_ipflow_dag.get_input_data scheduled__2023-07-29T00:00:00+00:00 [queued]>
[2023-07-30T00:15:19.883+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: dbt_ipflow_dag.get_input_data scheduled__2023-07-29T00:00:00+00:00 [queued]>
[2023-07-30T00:15:19.884+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-07-30T00:15:19.886+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2023-07-30T00:15:19.888+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-07-30T00:15:19.902+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): get_input_data> on 2023-07-29 00:00:00+00:00
[2023-07-30T00:15:19.912+0000] {standard_task_runner.py:55} INFO - Started process 21419 to run task
[2023-07-30T00:15:19.919+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dbt_ipflow_dag', 'get_input_data', 'scheduled__2023-07-29T00:00:00+00:00', '--job-id', '91', '--raw', '--subdir', 'DAGS_FOLDER/dbt_ip_flow_dag.py', '--cfg-path', '/tmp/tmplfvx0jjo']
[2023-07-30T00:15:19.926+0000] {standard_task_runner.py:83} INFO - Job 91: Subtask get_input_data
[2023-07-30T00:15:20.021+0000] {task_command.py:389} INFO - Running <TaskInstance: dbt_ipflow_dag.get_input_data scheduled__2023-07-29T00:00:00+00:00 [running]> on host 635f1a4ac995
[2023-07-30T00:15:20.115+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dbt_ipflow_dag
AIRFLOW_CTX_TASK_ID=get_input_data
AIRFLOW_CTX_EXECUTION_DATE=2023-07-29T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-07-29T00:00:00+00:00
[2023-07-30T00:15:20.123+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-07-30T00:15:20.124+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', "dbt run --select stg_ipflow_input_data --profiles-dir /opt/***/dbt/dbt_dsg_app --project-dir /opt/***/dbt/dbt_dsg_app  --target dev --vars '{'env': 'dev'}' "]
[2023-07-30T00:15:20.144+0000] {subprocess.py:86} INFO - Output:
[2023-07-30T00:15:22.021+0000] {subprocess.py:93} INFO - [0m00:15:22  Running with dbt=1.5.1
[2023-07-30T00:15:22.873+0000] {subprocess.py:93} INFO - [0m00:15:22  Found 12 models, 2 tests, 0 snapshots, 0 analyses, 321 macros, 0 operations, 0 seed files, 0 sources, 0 exposures, 0 metrics, 0 groups
[2023-07-30T00:15:22.878+0000] {subprocess.py:93} INFO - [0m00:15:22
[2023-07-30T00:15:23.771+0000] {subprocess.py:93} INFO - [0m00:15:23
[2023-07-30T00:15:23.774+0000] {subprocess.py:93} INFO - [0m00:15:23  Finished running  in 0 hours 0 minutes and 0.89 seconds (0.89s).
[2023-07-30T00:15:23.784+0000] {subprocess.py:93} INFO - [0m00:15:23  Encountered an error:
[2023-07-30T00:15:23.785+0000] {subprocess.py:93} INFO - Runtime Error
[2023-07-30T00:15:23.786+0000] {subprocess.py:93} INFO -   Database error while listing schemas in database "DEV_QA"
[2023-07-30T00:15:23.787+0000] {subprocess.py:93} INFO -   Database Error
[2023-07-30T00:15:23.788+0000] {subprocess.py:93} INFO -     250001 (08001): Failed to connect to DB: bcb55215.us-east-1.snowflakecomputing.com:443. Incorrect username or password was specified.
[2023-07-30T00:15:24.299+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-07-30T00:15:24.319+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-07-30T00:15:24.325+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=dbt_ipflow_dag, task_id=get_input_data, execution_date=20230729T000000, start_date=20230730T001519, end_date=20230730T001524
[2023-07-30T00:15:24.339+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 91 for task get_input_data (Bash command failed. The command returned a non-zero exit code 2.; 21419)
[2023-07-30T00:15:24.371+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-07-30T00:15:24.393+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
