[2023-06-20T20:56:23.108+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: dbt_ipflow_dag.dbt_run manual__2023-06-20T20:54:11.483592+00:00 [queued]>
[2023-06-20T20:56:23.116+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: dbt_ipflow_dag.dbt_run manual__2023-06-20T20:54:11.483592+00:00 [queued]>
[2023-06-20T20:56:23.119+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-06-20T20:56:23.120+0000] {taskinstance.py:1284} INFO - Starting attempt 3 of 3
[2023-06-20T20:56:23.121+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-06-20T20:56:23.131+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): dbt_run> on 2023-06-20 20:54:11.483592+00:00
[2023-06-20T20:56:23.139+0000] {standard_task_runner.py:55} INFO - Started process 13679 to run task
[2023-06-20T20:56:23.145+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dbt_ipflow_dag', 'dbt_run', 'manual__2023-06-20T20:54:11.483592+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/dbt_ip_flow_dag.py', '--cfg-path', '/tmp/tmp3t89wc6g']
[2023-06-20T20:56:23.148+0000] {standard_task_runner.py:83} INFO - Job 17: Subtask dbt_run
[2023-06-20T20:56:23.259+0000] {task_command.py:389} INFO - Running <TaskInstance: dbt_ipflow_dag.dbt_run manual__2023-06-20T20:54:11.483592+00:00 [running]> on host 635f1a4ac995
[2023-06-20T20:56:23.321+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dbt_ipflow_dag
AIRFLOW_CTX_TASK_ID=dbt_run
AIRFLOW_CTX_EXECUTION_DATE=2023-06-20T20:54:11.483592+00:00
AIRFLOW_CTX_TRY_NUMBER=3
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-06-20T20:54:11.483592+00:00
[2023-06-20T20:56:23.324+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-06-20T20:56:23.325+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'source /opt/***/dbt_venv/bin/activate && cd /opt/***/dbt/dbt_dsg_app && dbt run --models .']
[2023-06-20T20:56:23.341+0000] {subprocess.py:86} INFO - Output:
[2023-06-20T20:56:23.357+0000] {subprocess.py:93} INFO - /bin/bash: line 1: dbt: command not found
[2023-06-20T20:56:23.359+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2023-06-20T20:56:23.374+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-06-20T20:56:23.389+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=dbt_ipflow_dag, task_id=dbt_run, execution_date=20230620T205411, start_date=20230620T205623, end_date=20230620T205623
[2023-06-20T20:56:23.407+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 17 for task dbt_run (Bash command failed. The command returned a non-zero exit code 127.; 13679)
[2023-06-20T20:56:23.436+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-06-20T20:56:23.460+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
