[2023-06-20T21:50:48.269+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: dbt_ipflow_dag.dbt_run manual__2023-06-20T20:54:11.483592+00:00 [queued]>
[2023-06-20T21:50:48.280+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: dbt_ipflow_dag.dbt_run manual__2023-06-20T20:54:11.483592+00:00 [queued]>
[2023-06-20T21:50:48.281+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-06-20T21:50:48.282+0000] {taskinstance.py:1284} INFO - Starting attempt 5 of 5
[2023-06-20T21:50:48.284+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-06-20T21:50:48.294+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): dbt_run> on 2023-06-20 20:54:11.483592+00:00
[2023-06-20T21:50:48.302+0000] {standard_task_runner.py:55} INFO - Started process 17142 to run task
[2023-06-20T21:50:48.307+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dbt_ipflow_dag', 'dbt_run', 'manual__2023-06-20T20:54:11.483592+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/dbt_ip_flow_dag.py', '--cfg-path', '/tmp/tmpilsqknra']
[2023-06-20T21:50:48.312+0000] {standard_task_runner.py:83} INFO - Job 19: Subtask dbt_run
[2023-06-20T21:50:48.380+0000] {task_command.py:389} INFO - Running <TaskInstance: dbt_ipflow_dag.dbt_run manual__2023-06-20T20:54:11.483592+00:00 [running]> on host 635f1a4ac995
[2023-06-20T21:50:48.441+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dbt_ipflow_dag
AIRFLOW_CTX_TASK_ID=dbt_run
AIRFLOW_CTX_EXECUTION_DATE=2023-06-20T20:54:11.483592+00:00
AIRFLOW_CTX_TRY_NUMBER=5
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-06-20T20:54:11.483592+00:00
[2023-06-20T21:50:48.444+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-06-20T21:50:48.446+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cd /opt/***/dbt/dbt_dsg_app && dbt debug']
[2023-06-20T21:50:48.473+0000] {subprocess.py:86} INFO - Output:
[2023-06-20T21:50:48.479+0000] {subprocess.py:93} INFO - /bin/bash: line 1: dbt: command not found
[2023-06-20T21:50:48.481+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2023-06-20T21:50:48.494+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-06-20T21:50:48.499+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=dbt_ipflow_dag, task_id=dbt_run, execution_date=20230620T205411, start_date=20230620T215048, end_date=20230620T215048
[2023-06-20T21:50:48.509+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 19 for task dbt_run (Bash command failed. The command returned a non-zero exit code 127.; 17142)
[2023-06-20T21:50:48.525+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-06-20T21:50:48.544+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
