[2023-06-20T21:02:12.048+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: dbt_ipflow_dag.dbt_run manual__2023-06-20T20:54:11.483592+00:00 [queued]>
[2023-06-20T21:02:12.057+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: dbt_ipflow_dag.dbt_run manual__2023-06-20T20:54:11.483592+00:00 [queued]>
[2023-06-20T21:02:12.059+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-06-20T21:02:12.069+0000] {taskinstance.py:1284} INFO - Starting attempt 4 of 4
[2023-06-20T21:02:12.071+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-06-20T21:02:12.082+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): dbt_run> on 2023-06-20 20:54:11.483592+00:00
[2023-06-20T21:02:12.093+0000] {standard_task_runner.py:55} INFO - Started process 14054 to run task
[2023-06-20T21:02:12.103+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dbt_ipflow_dag', 'dbt_run', 'manual__2023-06-20T20:54:11.483592+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/dbt_ip_flow_dag.py', '--cfg-path', '/tmp/tmprq_ued_i']
[2023-06-20T21:02:12.107+0000] {standard_task_runner.py:83} INFO - Job 18: Subtask dbt_run
[2023-06-20T21:02:12.209+0000] {task_command.py:389} INFO - Running <TaskInstance: dbt_ipflow_dag.dbt_run manual__2023-06-20T20:54:11.483592+00:00 [running]> on host 635f1a4ac995
[2023-06-20T21:02:12.273+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dbt_ipflow_dag
AIRFLOW_CTX_TASK_ID=dbt_run
AIRFLOW_CTX_EXECUTION_DATE=2023-06-20T20:54:11.483592+00:00
AIRFLOW_CTX_TRY_NUMBER=4
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-06-20T20:54:11.483592+00:00
[2023-06-20T21:02:12.276+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-06-20T21:02:12.278+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'source /opt/***/dbt_venv/bin/activate && cd /opt/***/dbt/dbt_dsg_app && dbt debug']
[2023-06-20T21:02:12.294+0000] {subprocess.py:86} INFO - Output:
[2023-06-20T21:02:12.301+0000] {subprocess.py:93} INFO - /bin/bash: line 1: dbt: command not found
[2023-06-20T21:02:12.304+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2023-06-20T21:02:12.317+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-06-20T21:02:12.322+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=dbt_ipflow_dag, task_id=dbt_run, execution_date=20230620T205411, start_date=20230620T210212, end_date=20230620T210212
[2023-06-20T21:02:12.332+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 18 for task dbt_run (Bash command failed. The command returned a non-zero exit code 127.; 14054)
[2023-06-20T21:02:12.354+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-06-20T21:02:12.372+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
