[2023-06-20T22:02:42.378+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: dbt_ipflow_dag.dbt_run_3 manual__2023-06-20T22:02:38.038689+00:00 [queued]>
[2023-06-20T22:02:42.386+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: dbt_ipflow_dag.dbt_run_3 manual__2023-06-20T22:02:38.038689+00:00 [queued]>
[2023-06-20T22:02:42.388+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-06-20T22:02:42.389+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2023-06-20T22:02:42.390+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-06-20T22:02:42.400+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): dbt_run_3> on 2023-06-20 22:02:38.038689+00:00
[2023-06-20T22:02:42.406+0000] {standard_task_runner.py:55} INFO - Started process 17911 to run task
[2023-06-20T22:02:42.411+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dbt_ipflow_dag', 'dbt_run_3', 'manual__2023-06-20T22:02:38.038689+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/dbt_ip_flow_dag.py', '--cfg-path', '/tmp/tmpv4qyjyh8']
[2023-06-20T22:02:42.414+0000] {standard_task_runner.py:83} INFO - Job 25: Subtask dbt_run_3
[2023-06-20T22:02:42.481+0000] {task_command.py:389} INFO - Running <TaskInstance: dbt_ipflow_dag.dbt_run_3 manual__2023-06-20T22:02:38.038689+00:00 [running]> on host 635f1a4ac995
[2023-06-20T22:02:42.539+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dbt_ipflow_dag
AIRFLOW_CTX_TASK_ID=dbt_run_3
AIRFLOW_CTX_EXECUTION_DATE=2023-06-20T22:02:38.038689+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-06-20T22:02:38.038689+00:00
[2023-06-20T22:02:42.542+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-06-20T22:02:42.581+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'dbt debug']
[2023-06-20T22:02:42.595+0000] {subprocess.py:86} INFO - Output:
[2023-06-20T22:02:42.598+0000] {subprocess.py:93} INFO - /bin/bash: line 1: dbt: command not found
[2023-06-20T22:02:42.599+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2023-06-20T22:02:42.612+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-06-20T22:02:42.617+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=dbt_ipflow_dag, task_id=dbt_run_3, execution_date=20230620T220238, start_date=20230620T220242, end_date=20230620T220242
[2023-06-20T22:02:42.628+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 25 for task dbt_run_3 (Bash command failed. The command returned a non-zero exit code 127.; 17911)
[2023-06-20T22:02:42.667+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-06-20T22:02:42.684+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
