[2023-06-20T23:18:39.293+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: dbt_ipflow_dag.dbt_run_3 manual__2023-06-20T22:02:38.038689+00:00 [queued]>
[2023-06-20T23:18:39.300+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: dbt_ipflow_dag.dbt_run_3 manual__2023-06-20T22:02:38.038689+00:00 [queued]>
[2023-06-20T23:18:39.302+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-06-20T23:18:39.303+0000] {taskinstance.py:1284} INFO - Starting attempt 3 of 3
[2023-06-20T23:18:39.313+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-06-20T23:18:39.322+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): dbt_run_3> on 2023-06-20 22:02:38.038689+00:00
[2023-06-20T23:18:39.330+0000] {standard_task_runner.py:55} INFO - Started process 22749 to run task
[2023-06-20T23:18:39.334+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dbt_ipflow_dag', 'dbt_run_3', 'manual__2023-06-20T22:02:38.038689+00:00', '--job-id', '27', '--raw', '--subdir', 'DAGS_FOLDER/dbt_ip_flow_dag.py', '--cfg-path', '/tmp/tmpgytjtpni']
[2023-06-20T23:18:39.337+0000] {standard_task_runner.py:83} INFO - Job 27: Subtask dbt_run_3
[2023-06-20T23:18:39.406+0000] {task_command.py:389} INFO - Running <TaskInstance: dbt_ipflow_dag.dbt_run_3 manual__2023-06-20T22:02:38.038689+00:00 [running]> on host 635f1a4ac995
[2023-06-20T23:18:39.485+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dbt_ipflow_dag
AIRFLOW_CTX_TASK_ID=dbt_run_3
AIRFLOW_CTX_EXECUTION_DATE=2023-06-20T22:02:38.038689+00:00
AIRFLOW_CTX_TRY_NUMBER=3
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-06-20T22:02:38.038689+00:00
[2023-06-20T23:18:39.488+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-06-20T23:18:39.490+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'dbt run --profiles-dir /opt/***/dbt/dbt_dsg_app --project-dir /opt/***/dbt/dbt_dsg_app']
[2023-06-20T23:18:39.507+0000] {subprocess.py:86} INFO - Output:
[2023-06-20T23:18:39.512+0000] {subprocess.py:93} INFO - /bin/bash: line 1: dbt: command not found
[2023-06-20T23:18:39.513+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2023-06-20T23:18:39.527+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-06-20T23:18:39.532+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=dbt_ipflow_dag, task_id=dbt_run_3, execution_date=20230620T220238, start_date=20230620T231839, end_date=20230620T231839
[2023-06-20T23:18:39.543+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 27 for task dbt_run_3 (Bash command failed. The command returned a non-zero exit code 127.; 22749)
[2023-06-20T23:18:39.588+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-06-20T23:18:39.606+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
