[2023-06-26T18:49:36.200+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: dbt_ipflow_dag.get_input_data scheduled__2023-06-25T00:00:00+00:00 [queued]>
[2023-06-26T18:49:36.209+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: dbt_ipflow_dag.get_input_data scheduled__2023-06-25T00:00:00+00:00 [queued]>
[2023-06-26T18:49:36.211+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-06-26T18:49:36.213+0000] {taskinstance.py:1284} INFO - Starting attempt 3 of 3
[2023-06-26T18:49:36.217+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-06-26T18:49:36.227+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): get_input_data> on 2023-06-25 00:00:00+00:00
[2023-06-26T18:49:36.233+0000] {standard_task_runner.py:55} INFO - Started process 26592 to run task
[2023-06-26T18:49:36.238+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dbt_ipflow_dag', 'get_input_data', 'scheduled__2023-06-25T00:00:00+00:00', '--job-id', '62', '--raw', '--subdir', 'DAGS_FOLDER/dbt_ip_flow_dag.py', '--cfg-path', '/tmp/tmpgezl51gv']
[2023-06-26T18:49:36.241+0000] {standard_task_runner.py:83} INFO - Job 62: Subtask get_input_data
[2023-06-26T18:49:36.310+0000] {task_command.py:389} INFO - Running <TaskInstance: dbt_ipflow_dag.get_input_data scheduled__2023-06-25T00:00:00+00:00 [running]> on host 635f1a4ac995
[2023-06-26T18:49:36.375+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dbt_ipflow_dag
AIRFLOW_CTX_TASK_ID=get_input_data
AIRFLOW_CTX_EXECUTION_DATE=2023-06-25T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=3
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-06-25T00:00:00+00:00
[2023-06-26T18:49:36.379+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-06-26T18:49:36.380+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', "dbt run --select stg_ipflow_input_data --profiles-dir /opt/***/dbt/dbt_dsg_app --project-dir /opt/***/dbt/dbt_dsg_app  --target DEV --vars {'env': 'DEV'} "]
[2023-06-26T18:49:36.396+0000] {subprocess.py:86} INFO - Output:
[2023-06-26T18:49:37.858+0000] {subprocess.py:93} INFO - [0m18:49:37  The YAML provided in the --vars argument is not valid.
[2023-06-26T18:49:37.874+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-06-26T18:49:37.875+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/dbt/clients/yaml_helper.py", line 56, in load_yaml_text
[2023-06-26T18:49:37.876+0000] {subprocess.py:93} INFO -     return safe_load(contents)
[2023-06-26T18:49:37.880+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/dbt/clients/yaml_helper.py", line 51, in safe_load
[2023-06-26T18:49:37.881+0000] {subprocess.py:93} INFO -     return yaml.load(contents, Loader=SafeLoader)
[2023-06-26T18:49:37.883+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/yaml/__init__.py", line 81, in load
[2023-06-26T18:49:37.884+0000] {subprocess.py:93} INFO -     return loader.get_single_data()
[2023-06-26T18:49:37.885+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/yaml/constructor.py", line 49, in get_single_data
[2023-06-26T18:49:37.886+0000] {subprocess.py:93} INFO -     node = self.get_single_node()
[2023-06-26T18:49:37.887+0000] {subprocess.py:93} INFO -   File "yaml/_yaml.pyx", line 673, in yaml._yaml.CParser.get_single_node
[2023-06-26T18:49:37.888+0000] {subprocess.py:93} INFO -   File "yaml/_yaml.pyx", line 687, in yaml._yaml.CParser._compose_document
[2023-06-26T18:49:37.889+0000] {subprocess.py:93} INFO -   File "yaml/_yaml.pyx", line 731, in yaml._yaml.CParser._compose_node
[2023-06-26T18:49:37.891+0000] {subprocess.py:93} INFO -   File "yaml/_yaml.pyx", line 845, in yaml._yaml.CParser._compose_mapping_node
[2023-06-26T18:49:37.897+0000] {subprocess.py:93} INFO -   File "yaml/_yaml.pyx", line 694, in yaml._yaml.CParser._compose_node
[2023-06-26T18:49:37.899+0000] {subprocess.py:93} INFO -   File "yaml/_yaml.pyx", line 860, in yaml._yaml.CParser._parse_next_event
[2023-06-26T18:49:37.900+0000] {subprocess.py:93} INFO - yaml.parser.ParserError: while parsing a flow node
[2023-06-26T18:49:37.901+0000] {subprocess.py:93} INFO - did not find expected node content
[2023-06-26T18:49:37.902+0000] {subprocess.py:93} INFO -   in "<unicode string>", line 2, column 1
[2023-06-26T18:49:37.903+0000] {subprocess.py:93} INFO - 
[2023-06-26T18:49:37.905+0000] {subprocess.py:93} INFO - During handling of the above exception, another exception occurred:
[2023-06-26T18:49:37.906+0000] {subprocess.py:93} INFO - 
[2023-06-26T18:49:37.907+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-06-26T18:49:37.916+0000] {subprocess.py:93} INFO -   File "/home/***/.local/bin/dbt", line 8, in <module>
[2023-06-26T18:49:37.917+0000] {subprocess.py:93} INFO -     sys.exit(cli())
[2023-06-26T18:49:37.918+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/click/core.py", line 1130, in __call__
[2023-06-26T18:49:37.919+0000] {subprocess.py:93} INFO -     return self.main(*args, **kwargs)
[2023-06-26T18:49:37.920+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/click/core.py", line 1055, in main
[2023-06-26T18:49:37.922+0000] {subprocess.py:93} INFO -     rv = self.invoke(ctx)
[2023-06-26T18:49:37.922+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/click/core.py", line 1655, in invoke
[2023-06-26T18:49:37.923+0000] {subprocess.py:93} INFO -     sub_ctx = cmd.make_context(cmd_name, args, parent=ctx)
[2023-06-26T18:49:37.924+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/click/core.py", line 920, in make_context
[2023-06-26T18:49:37.925+0000] {subprocess.py:93} INFO -     self.parse_args(ctx, args)
[2023-06-26T18:49:37.930+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/click/core.py", line 1378, in parse_args
[2023-06-26T18:49:37.931+0000] {subprocess.py:93} INFO -     value, args = param.handle_parse_result(ctx, opts, args)
[2023-06-26T18:49:37.932+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/click/core.py", line 2360, in handle_parse_result
[2023-06-26T18:49:37.933+0000] {subprocess.py:93} INFO -     value = self.process_value(ctx, value)
[2023-06-26T18:49:37.934+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/click/core.py", line 2316, in process_value
[2023-06-26T18:49:37.935+0000] {subprocess.py:93} INFO -     value = self.type_cast_value(ctx, value)
[2023-06-26T18:49:37.936+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/click/core.py", line 2304, in type_cast_value
[2023-06-26T18:49:37.937+0000] {subprocess.py:93} INFO -     return convert(value)
[2023-06-26T18:49:37.938+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/click/types.py", line 82, in __call__
[2023-06-26T18:49:37.939+0000] {subprocess.py:93} INFO -     return self.convert(value, param, ctx)
[2023-06-26T18:49:37.940+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/dbt/cli/option_types.py", line 19, in convert
[2023-06-26T18:49:37.941+0000] {subprocess.py:93} INFO -     return parse_cli_vars(value)
[2023-06-26T18:49:37.942+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/dbt/config/utils.py", line 11, in parse_cli_vars
[2023-06-26T18:49:37.943+0000] {subprocess.py:93} INFO -     return parse_cli_yaml_string(var_string, "vars")
[2023-06-26T18:49:37.944+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/dbt/config/utils.py", line 16, in parse_cli_yaml_string
[2023-06-26T18:49:37.945+0000] {subprocess.py:93} INFO -     cli_vars = yaml_helper.load_yaml_text(var_string)
[2023-06-26T18:49:37.946+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/dbt/clients/yaml_helper.py", line 63, in load_yaml_text
[2023-06-26T18:49:37.948+0000] {subprocess.py:93} INFO -     raise dbt.exceptions.DbtValidationError(error)
[2023-06-26T18:49:37.949+0000] {subprocess.py:93} INFO - dbt.exceptions.DbtValidationError: Runtime Error
[2023-06-26T18:49:37.951+0000] {subprocess.py:93} INFO -   Syntax error near line 2
[2023-06-26T18:49:37.953+0000] {subprocess.py:93} INFO -   ------------------------------
[2023-06-26T18:49:37.954+0000] {subprocess.py:93} INFO -   1  | {env:
[2023-06-26T18:49:37.955+0000] {subprocess.py:93} INFO - 
[2023-06-26T18:49:37.956+0000] {subprocess.py:93} INFO -   Raw Error:
[2023-06-26T18:49:37.957+0000] {subprocess.py:93} INFO -   ------------------------------
[2023-06-26T18:49:37.958+0000] {subprocess.py:93} INFO -   while parsing a flow node
[2023-06-26T18:49:37.959+0000] {subprocess.py:93} INFO -   did not find expected node content
[2023-06-26T18:49:37.960+0000] {subprocess.py:93} INFO -     in "<unicode string>", line 2, column 1
[2023-06-26T18:49:37.986+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-06-26T18:49:38.000+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-06-26T18:49:38.006+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=dbt_ipflow_dag, task_id=get_input_data, execution_date=20230625T000000, start_date=20230626T184936, end_date=20230626T184938
[2023-06-26T18:49:38.023+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 62 for task get_input_data (Bash command failed. The command returned a non-zero exit code 1.; 26592)
[2023-06-26T18:49:38.056+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-06-26T18:49:38.081+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
