[2023-08-04T17:25:16.843+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: dbt_ipflow_dag.get_input_data scheduled__2023-08-03T00:00:00+00:00 [queued]>
[2023-08-04T17:25:16.853+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: dbt_ipflow_dag.get_input_data scheduled__2023-08-03T00:00:00+00:00 [queued]>
[2023-08-04T17:25:16.855+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-08-04T17:25:16.856+0000] {taskinstance.py:1284} INFO - Starting attempt 2 of 2
[2023-08-04T17:25:16.858+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-08-04T17:25:16.869+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): get_input_data> on 2023-08-03 00:00:00+00:00
[2023-08-04T17:25:16.879+0000] {standard_task_runner.py:55} INFO - Started process 191 to run task
[2023-08-04T17:25:16.884+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dbt_ipflow_dag', 'get_input_data', 'scheduled__2023-08-03T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/dbt_ip_flow_dag.py', '--cfg-path', '/tmp/tmpazvahdid']
[2023-08-04T17:25:16.887+0000] {standard_task_runner.py:83} INFO - Job 4: Subtask get_input_data
[2023-08-04T17:25:16.969+0000] {task_command.py:389} INFO - Running <TaskInstance: dbt_ipflow_dag.get_input_data scheduled__2023-08-03T00:00:00+00:00 [running]> on host e6719fd6f95b
[2023-08-04T17:25:17.043+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dbt_ipflow_dag
AIRFLOW_CTX_TASK_ID=get_input_data
AIRFLOW_CTX_EXECUTION_DATE=2023-08-03T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-08-03T00:00:00+00:00
[2023-08-04T17:25:17.045+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-08-04T17:25:17.047+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', "dbt run --select stg_ipflow_input_data --profiles-dir /opt/***/dbt/dbt_dsg_app --project-dir /opt/***/dbt/dbt_dsg_app  --target dev --vars '{'env': 'dev'}' "]
[2023-08-04T17:25:17.065+0000] {subprocess.py:86} INFO - Output:
[2023-08-04T17:25:17.068+0000] {subprocess.py:93} INFO - /bin/bash: line 1: dbt: command not found
[2023-08-04T17:25:17.070+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2023-08-04T17:25:17.085+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-08-04T17:25:17.091+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=dbt_ipflow_dag, task_id=get_input_data, execution_date=20230803T000000, start_date=20230804T172516, end_date=20230804T172517
[2023-08-04T17:25:17.108+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 4 for task get_input_data (Bash command failed. The command returned a non-zero exit code 127.; 191)
[2023-08-04T17:25:17.139+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-08-04T17:25:17.163+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-08-04T17:35:54.640+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: dbt_ipflow_dag.get_input_data scheduled__2023-08-03T00:00:00+00:00 [queued]>
[2023-08-04T17:35:54.657+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: dbt_ipflow_dag.get_input_data scheduled__2023-08-03T00:00:00+00:00 [queued]>
[2023-08-04T17:35:54.658+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-08-04T17:35:54.659+0000] {taskinstance.py:1284} INFO - Starting attempt 2 of 2
[2023-08-04T17:35:54.660+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-08-04T17:35:54.672+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): get_input_data> on 2023-08-03 00:00:00+00:00
[2023-08-04T17:35:54.679+0000] {standard_task_runner.py:55} INFO - Started process 203 to run task
[2023-08-04T17:35:54.683+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dbt_ipflow_dag', 'get_input_data', 'scheduled__2023-08-03T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/dbt_ip_flow_dag.py', '--cfg-path', '/tmp/tmpkz2oyhny']
[2023-08-04T17:35:54.692+0000] {standard_task_runner.py:83} INFO - Job 4: Subtask get_input_data
[2023-08-04T17:35:54.758+0000] {task_command.py:389} INFO - Running <TaskInstance: dbt_ipflow_dag.get_input_data scheduled__2023-08-03T00:00:00+00:00 [running]> on host 9817f6d599e1
[2023-08-04T17:35:54.813+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dbt_ipflow_dag
AIRFLOW_CTX_TASK_ID=get_input_data
AIRFLOW_CTX_EXECUTION_DATE=2023-08-03T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-08-03T00:00:00+00:00
[2023-08-04T17:35:54.816+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-08-04T17:35:54.817+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', "source /dbt_venv/bin/activate && dbt run --select stg_ipflow_input_data --profiles-dir /opt/***/dbt/dbt_dsg_app --project-dir /opt/***/dbt/dbt_dsg_app  --target dev --vars '{'env': 'dev'}' "]
[2023-08-04T17:35:54.832+0000] {subprocess.py:86} INFO - Output:
[2023-08-04T17:35:54.835+0000] {subprocess.py:93} INFO - /bin/bash: line 1: /dbt_venv/bin/activate: No such file or directory
[2023-08-04T17:35:54.836+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-08-04T17:35:54.849+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-08-04T17:35:54.854+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=dbt_ipflow_dag, task_id=get_input_data, execution_date=20230803T000000, start_date=20230804T173554, end_date=20230804T173554
[2023-08-04T17:35:54.864+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 4 for task get_input_data (Bash command failed. The command returned a non-zero exit code 1.; 203)
[2023-08-04T17:35:54.895+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-08-04T17:35:54.914+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-08-04T17:50:41.163+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: dbt_ipflow_dag.get_input_data scheduled__2023-08-03T00:00:00+00:00 [queued]>
[2023-08-04T17:50:41.171+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: dbt_ipflow_dag.get_input_data scheduled__2023-08-03T00:00:00+00:00 [queued]>
[2023-08-04T17:50:41.172+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-08-04T17:50:41.174+0000] {taskinstance.py:1284} INFO - Starting attempt 2 of 2
[2023-08-04T17:50:41.175+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-08-04T17:50:41.184+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): get_input_data> on 2023-08-03 00:00:00+00:00
[2023-08-04T17:50:41.191+0000] {standard_task_runner.py:55} INFO - Started process 599 to run task
[2023-08-04T17:50:41.195+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dbt_ipflow_dag', 'get_input_data', 'scheduled__2023-08-03T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/dbt_ip_flow_dag.py', '--cfg-path', '/tmp/tmpaxsokjnr']
[2023-08-04T17:50:41.205+0000] {standard_task_runner.py:83} INFO - Job 4: Subtask get_input_data
[2023-08-04T17:50:41.272+0000] {task_command.py:389} INFO - Running <TaskInstance: dbt_ipflow_dag.get_input_data scheduled__2023-08-03T00:00:00+00:00 [running]> on host 1c85b9f3c91c
[2023-08-04T17:50:41.330+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dbt_ipflow_dag
AIRFLOW_CTX_TASK_ID=get_input_data
AIRFLOW_CTX_EXECUTION_DATE=2023-08-03T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-08-03T00:00:00+00:00
[2023-08-04T17:50:41.333+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-08-04T17:50:41.334+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', "source dbt_venv/bin/activate && dbt run --select stg_ipflow_input_data --profiles-dir /opt/***/dbt/dbt_dsg_app --project-dir /opt/***/dbt/dbt_dsg_app  --target dev --vars '{'env': 'dev'}' "]
[2023-08-04T17:50:41.350+0000] {subprocess.py:86} INFO - Output:
[2023-08-04T17:50:41.357+0000] {subprocess.py:93} INFO - /bin/bash: line 1: dbt_venv/bin/activate: No such file or directory
[2023-08-04T17:50:41.358+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-08-04T17:50:41.371+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-08-04T17:50:41.375+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=dbt_ipflow_dag, task_id=get_input_data, execution_date=20230803T000000, start_date=20230804T175041, end_date=20230804T175041
[2023-08-04T17:50:41.388+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 4 for task get_input_data (Bash command failed. The command returned a non-zero exit code 1.; 599)
[2023-08-04T17:50:41.409+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-08-04T17:50:41.427+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-08-04T18:03:00.060+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: dbt_ipflow_dag.get_input_data scheduled__2023-08-03T00:00:00+00:00 [queued]>
[2023-08-04T18:03:00.072+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: dbt_ipflow_dag.get_input_data scheduled__2023-08-03T00:00:00+00:00 [queued]>
[2023-08-04T18:03:00.083+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-08-04T18:03:00.084+0000] {taskinstance.py:1284} INFO - Starting attempt 2 of 2
[2023-08-04T18:03:00.086+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-08-04T18:03:00.097+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): get_input_data> on 2023-08-03 00:00:00+00:00
[2023-08-04T18:03:00.106+0000] {standard_task_runner.py:55} INFO - Started process 404 to run task
[2023-08-04T18:03:00.113+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dbt_ipflow_dag', 'get_input_data', 'scheduled__2023-08-03T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/dbt_ip_flow_dag.py', '--cfg-path', '/tmp/tmphnfokmun']
[2023-08-04T18:03:00.117+0000] {standard_task_runner.py:83} INFO - Job 4: Subtask get_input_data
[2023-08-04T18:03:00.220+0000] {task_command.py:389} INFO - Running <TaskInstance: dbt_ipflow_dag.get_input_data scheduled__2023-08-03T00:00:00+00:00 [running]> on host ebb8780b02cb
[2023-08-04T18:03:00.298+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dbt_ipflow_dag
AIRFLOW_CTX_TASK_ID=get_input_data
AIRFLOW_CTX_EXECUTION_DATE=2023-08-03T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-08-03T00:00:00+00:00
[2023-08-04T18:03:00.304+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-08-04T18:03:00.306+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', "source /opt/***/dbt_venv/bin/activate && dbt run --select stg_ipflow_input_data --profiles-dir /opt/***/dbt/dbt_dsg_app --project-dir /opt/***/dbt/dbt_dsg_app  --target dev --vars '{'env': 'dev'}' "]
[2023-08-04T18:03:00.325+0000] {subprocess.py:86} INFO - Output:
[2023-08-04T18:03:00.339+0000] {subprocess.py:93} INFO - /bin/bash: line 1: dbt: command not found
[2023-08-04T18:03:00.341+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2023-08-04T18:03:00.380+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-08-04T18:03:00.387+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=dbt_ipflow_dag, task_id=get_input_data, execution_date=20230803T000000, start_date=20230804T180300, end_date=20230804T180300
[2023-08-04T18:03:00.401+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 4 for task get_input_data (Bash command failed. The command returned a non-zero exit code 127.; 404)
[2023-08-04T18:03:00.486+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-08-04T18:03:00.512+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-08-04T18:12:31.867+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: dbt_ipflow_dag.get_input_data scheduled__2023-08-03T00:00:00+00:00 [queued]>
[2023-08-04T18:12:31.874+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: dbt_ipflow_dag.get_input_data scheduled__2023-08-03T00:00:00+00:00 [queued]>
[2023-08-04T18:12:31.875+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-08-04T18:12:31.877+0000] {taskinstance.py:1284} INFO - Starting attempt 2 of 2
[2023-08-04T18:12:31.878+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-08-04T18:12:31.886+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): get_input_data> on 2023-08-03 00:00:00+00:00
[2023-08-04T18:12:31.897+0000] {standard_task_runner.py:55} INFO - Started process 246 to run task
[2023-08-04T18:12:31.902+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dbt_ipflow_dag', 'get_input_data', 'scheduled__2023-08-03T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/dbt_ip_flow_dag.py', '--cfg-path', '/tmp/tmp7zwccwf0']
[2023-08-04T18:12:31.905+0000] {standard_task_runner.py:83} INFO - Job 4: Subtask get_input_data
[2023-08-04T18:12:31.995+0000] {task_command.py:389} INFO - Running <TaskInstance: dbt_ipflow_dag.get_input_data scheduled__2023-08-03T00:00:00+00:00 [running]> on host 2d3cfeb384b0
[2023-08-04T18:12:32.051+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dbt_ipflow_dag
AIRFLOW_CTX_TASK_ID=get_input_data
AIRFLOW_CTX_EXECUTION_DATE=2023-08-03T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-08-03T00:00:00+00:00
[2023-08-04T18:12:32.054+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-08-04T18:12:32.055+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', "pip install dbt-snowflake && dbt run --select stg_ipflow_input_data --profiles-dir /opt/***/dbt/dbt_dsg_app --project-dir /opt/***/dbt/dbt_dsg_app  --target dev --vars '{'env': 'dev'}' "]
[2023-08-04T18:12:32.070+0000] {subprocess.py:86} INFO - Output:
[2023-08-04T18:12:32.738+0000] {subprocess.py:93} INFO - Defaulting to user installation because normal site-packages is not writeable
[2023-08-04T18:12:33.048+0000] {subprocess.py:93} INFO - Collecting dbt-snowflake
[2023-08-04T18:12:33.145+0000] {subprocess.py:93} INFO -   Downloading dbt_snowflake-1.5.1-py3-none-any.whl (31 kB)
[2023-08-04T18:12:33.202+0000] {subprocess.py:93} INFO - Collecting dbt-core~=1.5.0 (from dbt-snowflake)
[2023-08-04T18:12:33.226+0000] {subprocess.py:93} INFO -   Downloading dbt_core-1.5.4-py3-none-any.whl (950 kB)
[2023-08-04T18:12:33.371+0000] {subprocess.py:93} INFO -      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 950.3/950.3 kB 6.6 MB/s eta 0:00:00
[2023-08-04T18:12:33.375+0000] {subprocess.py:93} INFO - Requirement already satisfied: snowflake-connector-python[secure-local-storage]~=3.0 in /home/***/.local/lib/python3.7/site-packages (from dbt-snowflake) (3.0.4)
[2023-08-04T18:12:33.393+0000] {subprocess.py:93} INFO - Requirement already satisfied: Jinja2==3.1.2 in /home/***/.local/lib/python3.7/site-packages (from dbt-core~=1.5.0->dbt-snowflake) (3.1.2)
[2023-08-04T18:12:33.414+0000] {subprocess.py:93} INFO - Collecting agate<1.7.1,>=1.6 (from dbt-core~=1.5.0->dbt-snowflake)
[2023-08-04T18:12:33.435+0000] {subprocess.py:93} INFO -   Downloading agate-1.7.0-py2.py3-none-any.whl (97 kB)
[2023-08-04T18:12:33.443+0000] {subprocess.py:93} INFO -      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.1/97.1 kB 13.8 MB/s eta 0:00:00
[2023-08-04T18:12:33.446+0000] {subprocess.py:93} INFO - Requirement already satisfied: click<8.1.4,>=7.0 in /home/***/.local/lib/python3.7/site-packages (from dbt-core~=1.5.0->dbt-snowflake) (8.1.3)
[2023-08-04T18:12:33.447+0000] {subprocess.py:93} INFO - Requirement already satisfied: colorama<0.4.7,>=0.3.9 in /home/***/.local/lib/python3.7/site-packages (from dbt-core~=1.5.0->dbt-snowflake) (0.4.4)
[2023-08-04T18:12:33.467+0000] {subprocess.py:93} INFO - Collecting hologram<=0.0.16,>=0.0.14 (from dbt-core~=1.5.0->dbt-snowflake)
[2023-08-04T18:12:33.488+0000] {subprocess.py:93} INFO -   Downloading hologram-0.0.16-py3-none-any.whl (11 kB)
[2023-08-04T18:12:33.492+0000] {subprocess.py:93} INFO - Requirement already satisfied: isodate<0.7,>=0.6 in /home/***/.local/lib/python3.7/site-packages (from dbt-core~=1.5.0->dbt-snowflake) (0.6.1)
[2023-08-04T18:12:33.518+0000] {subprocess.py:93} INFO - Collecting logbook<1.6,>=1.5 (from dbt-core~=1.5.0->dbt-snowflake)
[2023-08-04T18:12:33.554+0000] {subprocess.py:93} INFO -   Downloading Logbook-1.5.3.tar.gz (85 kB)
[2023-08-04T18:12:33.559+0000] {subprocess.py:93} INFO -      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 85.8/85.8 kB 18.9 MB/s eta 0:00:00
[2023-08-04T18:12:33.574+0000] {subprocess.py:93} INFO -   Preparing metadata (setup.py): started
[2023-08-04T18:12:34.083+0000] {subprocess.py:93} INFO -   Preparing metadata (setup.py): finished with status 'done'
[2023-08-04T18:12:34.128+0000] {subprocess.py:93} INFO - Collecting mashumaro[msgpack]==3.6 (from dbt-core~=1.5.0->dbt-snowflake)
[2023-08-04T18:12:34.148+0000] {subprocess.py:93} INFO -   Downloading mashumaro-3.6-py3-none-any.whl (66 kB)
[2023-08-04T18:12:34.164+0000] {subprocess.py:93} INFO -      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 66.5/66.5 kB 7.1 MB/s eta 0:00:00
[2023-08-04T18:12:34.181+0000] {subprocess.py:93} INFO - Collecting minimal-snowplow-tracker==0.0.2 (from dbt-core~=1.5.0->dbt-snowflake)
[2023-08-04T18:12:34.199+0000] {subprocess.py:93} INFO -   Downloading minimal-snowplow-tracker-0.0.2.tar.gz (12 kB)
[2023-08-04T18:12:34.206+0000] {subprocess.py:93} INFO -   Preparing metadata (setup.py): started
[2023-08-04T18:12:34.605+0000] {subprocess.py:93} INFO -   Preparing metadata (setup.py): finished with status 'done'
[2023-08-04T18:12:34.615+0000] {subprocess.py:93} INFO - Requirement already satisfied: packaging>20.9 in /home/***/.local/lib/python3.7/site-packages (from dbt-core~=1.5.0->dbt-snowflake) (21.3)
[2023-08-04T18:12:34.616+0000] {subprocess.py:93} INFO - Requirement already satisfied: sqlparse>=0.2.3 in /home/***/.local/lib/python3.7/site-packages (from dbt-core~=1.5.0->dbt-snowflake) (0.4.3)
[2023-08-04T18:12:34.647+0000] {subprocess.py:93} INFO - Collecting dbt-extractor~=0.4.1 (from dbt-core~=1.5.0->dbt-snowflake)
[2023-08-04T18:12:34.668+0000] {subprocess.py:93} INFO -   Downloading dbt_extractor-0.4.1-cp36-abi3-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (1.1 MB)
[2023-08-04T18:12:34.769+0000] {subprocess.py:93} INFO -      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 10.9 MB/s eta 0:00:00
[2023-08-04T18:12:34.772+0000] {subprocess.py:93} INFO - Requirement already satisfied: typing-extensions>=3.7.4 in /home/***/.local/lib/python3.7/site-packages (from dbt-core~=1.5.0->dbt-snowflake) (4.4.0)
[2023-08-04T18:12:34.773+0000] {subprocess.py:93} INFO - Requirement already satisfied: werkzeug<3,>=1 in /home/***/.local/lib/python3.7/site-packages (from dbt-core~=1.5.0->dbt-snowflake) (2.2.2)
[2023-08-04T18:12:34.775+0000] {subprocess.py:93} INFO - Requirement already satisfied: pathspec<0.12,>=0.9 in /home/***/.local/lib/python3.7/site-packages (from dbt-core~=1.5.0->dbt-snowflake) (0.9.0)
[2023-08-04T18:12:34.948+0000] {subprocess.py:93} INFO - Collecting protobuf>=4.0.0 (from dbt-core~=1.5.0->dbt-snowflake)
[2023-08-04T18:12:34.983+0000] {subprocess.py:93} INFO -   Downloading protobuf-4.23.4-cp37-abi3-manylinux2014_aarch64.whl (303 kB)
[2023-08-04T18:12:35.006+0000] {subprocess.py:93} INFO -      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 303.5/303.5 kB 14.8 MB/s eta 0:00:00
[2023-08-04T18:12:35.008+0000] {subprocess.py:93} INFO - Requirement already satisfied: pytz>=2015.7 in /home/***/.local/lib/python3.7/site-packages (from dbt-core~=1.5.0->dbt-snowflake) (2022.6)
[2023-08-04T18:12:35.009+0000] {subprocess.py:93} INFO - Requirement already satisfied: requests<3.0.0 in /home/***/.local/lib/python3.7/site-packages (from dbt-core~=1.5.0->dbt-snowflake) (2.28.1)
[2023-08-04T18:12:35.010+0000] {subprocess.py:93} INFO - Requirement already satisfied: idna<4,>=2.5 in /home/***/.local/lib/python3.7/site-packages (from dbt-core~=1.5.0->dbt-snowflake) (3.4)
[2023-08-04T18:12:35.011+0000] {subprocess.py:93} INFO - Requirement already satisfied: cffi<2.0.0,>=1.9 in /home/***/.local/lib/python3.7/site-packages (from dbt-core~=1.5.0->dbt-snowflake) (1.15.1)
[2023-08-04T18:12:35.071+0000] {subprocess.py:93} INFO - Collecting pyyaml>=6.0 (from dbt-core~=1.5.0->dbt-snowflake)
[2023-08-04T18:12:35.092+0000] {subprocess.py:93} INFO -   Downloading PyYAML-6.0.1-cp37-cp37m-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (658 kB)
[2023-08-04T18:12:35.161+0000] {subprocess.py:93} INFO -      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 658.4/658.4 kB 10.7 MB/s eta 0:00:00
[2023-08-04T18:12:35.193+0000] {subprocess.py:93} INFO - Collecting networkx<2.8.1,>=2.3 (from dbt-core~=1.5.0->dbt-snowflake)
[2023-08-04T18:12:35.212+0000] {subprocess.py:93} INFO -   Downloading networkx-2.6.3-py3-none-any.whl (1.9 MB)
[2023-08-04T18:12:35.418+0000] {subprocess.py:93} INFO -      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.9/1.9 MB 9.7 MB/s eta 0:00:00
[2023-08-04T18:12:35.425+0000] {subprocess.py:93} INFO - Requirement already satisfied: MarkupSafe>=2.0 in /home/***/.local/lib/python3.7/site-packages (from Jinja2==3.1.2->dbt-core~=1.5.0->dbt-snowflake) (2.1.1)
[2023-08-04T18:12:35.432+0000] {subprocess.py:93} INFO - Requirement already satisfied: msgpack>=0.5.6 in /home/***/.local/lib/python3.7/site-packages (from mashumaro[msgpack]==3.6->dbt-core~=1.5.0->dbt-snowflake) (1.0.4)
[2023-08-04T18:12:35.442+0000] {subprocess.py:93} INFO - Requirement already satisfied: six<2.0,>=1.9.0 in /home/***/.local/lib/python3.7/site-packages (from minimal-snowplow-tracker==0.0.2->dbt-core~=1.5.0->dbt-snowflake) (1.16.0)
[2023-08-04T18:12:35.451+0000] {subprocess.py:93} INFO - Requirement already satisfied: asn1crypto<2.0.0,>0.24.0 in /home/***/.local/lib/python3.7/site-packages (from snowflake-connector-python[secure-local-storage]~=3.0->dbt-snowflake) (1.5.1)
[2023-08-04T18:12:35.452+0000] {subprocess.py:93} INFO - Requirement already satisfied: cryptography<41.0.0,>=3.1.0 in /home/***/.local/lib/python3.7/site-packages (from snowflake-connector-python[secure-local-storage]~=3.0->dbt-snowflake) (36.0.2)
[2023-08-04T18:12:35.453+0000] {subprocess.py:93} INFO - Requirement already satisfied: oscrypto<2.0.0 in /home/***/.local/lib/python3.7/site-packages (from snowflake-connector-python[secure-local-storage]~=3.0->dbt-snowflake) (1.3.0)
[2023-08-04T18:12:35.454+0000] {subprocess.py:93} INFO - Requirement already satisfied: pyOpenSSL<24.0.0,>=16.2.0 in /home/***/.local/lib/python3.7/site-packages (from snowflake-connector-python[secure-local-storage]~=3.0->dbt-snowflake) (22.0.0)
[2023-08-04T18:12:35.455+0000] {subprocess.py:93} INFO - Requirement already satisfied: pycryptodomex!=3.5.0,<4.0.0,>=3.2 in /home/***/.local/lib/python3.7/site-packages (from snowflake-connector-python[secure-local-storage]~=3.0->dbt-snowflake) (3.18.0)
[2023-08-04T18:12:35.457+0000] {subprocess.py:93} INFO - Requirement already satisfied: pyjwt<3.0.0 in /home/***/.local/lib/python3.7/site-packages (from snowflake-connector-python[secure-local-storage]~=3.0->dbt-snowflake) (2.6.0)
[2023-08-04T18:12:35.457+0000] {subprocess.py:93} INFO - Requirement already satisfied: charset-normalizer<4,>=2 in /home/***/.local/lib/python3.7/site-packages (from snowflake-connector-python[secure-local-storage]~=3.0->dbt-snowflake) (2.1.1)
[2023-08-04T18:12:35.458+0000] {subprocess.py:93} INFO - Requirement already satisfied: urllib3<1.27,>=1.21.1 in /home/***/.local/lib/python3.7/site-packages (from snowflake-connector-python[secure-local-storage]~=3.0->dbt-snowflake) (1.26.13)
[2023-08-04T18:12:35.460+0000] {subprocess.py:93} INFO - Requirement already satisfied: certifi>=2017.4.17 in /home/***/.local/lib/python3.7/site-packages (from snowflake-connector-python[secure-local-storage]~=3.0->dbt-snowflake) (2022.9.24)
[2023-08-04T18:12:35.461+0000] {subprocess.py:93} INFO - Requirement already satisfied: filelock<4,>=3.5 in /home/***/.local/lib/python3.7/site-packages (from snowflake-connector-python[secure-local-storage]~=3.0->dbt-snowflake) (3.8.0)
[2023-08-04T18:12:35.463+0000] {subprocess.py:93} INFO - Requirement already satisfied: sortedcontainers>=2.4.0 in /home/***/.local/lib/python3.7/site-packages (from snowflake-connector-python[secure-local-storage]~=3.0->dbt-snowflake) (2.4.0)
[2023-08-04T18:12:35.464+0000] {subprocess.py:93} INFO - Requirement already satisfied: importlib-metadata in /home/***/.local/lib/python3.7/site-packages (from snowflake-connector-python[secure-local-storage]~=3.0->dbt-snowflake) (4.13.0)
[2023-08-04T18:12:35.512+0000] {subprocess.py:93} INFO - Collecting keyring!=16.1.0,<24.0.0 (from snowflake-connector-python[secure-local-storage]~=3.0->dbt-snowflake)
[2023-08-04T18:12:35.530+0000] {subprocess.py:93} INFO -   Downloading keyring-23.13.1-py3-none-any.whl (37 kB)
[2023-08-04T18:12:35.543+0000] {subprocess.py:93} INFO - Requirement already satisfied: Babel>=2.0 in /home/***/.local/lib/python3.7/site-packages (from agate<1.7.1,>=1.6->dbt-core~=1.5.0->dbt-snowflake) (2.11.0)
[2023-08-04T18:12:35.559+0000] {subprocess.py:93} INFO - Collecting leather>=0.3.2 (from agate<1.7.1,>=1.6->dbt-core~=1.5.0->dbt-snowflake)
[2023-08-04T18:12:35.578+0000] {subprocess.py:93} INFO -   Downloading leather-0.3.4-py2.py3-none-any.whl (31 kB)
[2023-08-04T18:12:35.631+0000] {subprocess.py:93} INFO - Collecting parsedatetime!=2.5,!=2.6,>=2.1 (from agate<1.7.1,>=1.6->dbt-core~=1.5.0->dbt-snowflake)
[2023-08-04T18:12:35.651+0000] {subprocess.py:93} INFO -   Downloading parsedatetime-2.4.tar.gz (58 kB)
[2023-08-04T18:12:35.655+0000] {subprocess.py:93} INFO -      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.8/58.8 kB 14.5 MB/s eta 0:00:00
[2023-08-04T18:12:35.668+0000] {subprocess.py:93} INFO -   Preparing metadata (setup.py): started
[2023-08-04T18:12:36.090+0000] {subprocess.py:93} INFO -   Preparing metadata (setup.py): finished with status 'done'
[2023-08-04T18:12:36.092+0000] {subprocess.py:93} INFO - Requirement already satisfied: python-slugify>=1.2.1 in /home/***/.local/lib/python3.7/site-packages (from agate<1.7.1,>=1.6->dbt-core~=1.5.0->dbt-snowflake) (7.0.0)
[2023-08-04T18:12:36.132+0000] {subprocess.py:93} INFO - Collecting pytimeparse>=1.1.5 (from agate<1.7.1,>=1.6->dbt-core~=1.5.0->dbt-snowflake)
[2023-08-04T18:12:36.150+0000] {subprocess.py:93} INFO -   Downloading pytimeparse-1.1.8-py2.py3-none-any.whl (10.0 kB)
[2023-08-04T18:12:36.158+0000] {subprocess.py:93} INFO - Requirement already satisfied: pycparser in /home/***/.local/lib/python3.7/site-packages (from cffi<2.0.0,>=1.9->dbt-core~=1.5.0->dbt-snowflake) (2.21)
[2023-08-04T18:12:36.182+0000] {subprocess.py:93} INFO - Requirement already satisfied: python-dateutil<2.9,>=2.8 in /home/***/.local/lib/python3.7/site-packages (from hologram<=0.0.16,>=0.0.14->dbt-core~=1.5.0->dbt-snowflake) (2.8.2)
[2023-08-04T18:12:36.183+0000] {subprocess.py:93} INFO - Requirement already satisfied: jsonschema>=3.0 in /home/***/.local/lib/python3.7/site-packages (from hologram<=0.0.16,>=0.0.14->dbt-core~=1.5.0->dbt-snowflake) (4.17.3)
[2023-08-04T18:12:36.217+0000] {subprocess.py:93} INFO - Collecting jaraco.classes (from keyring!=16.1.0,<24.0.0->snowflake-connector-python[secure-local-storage]~=3.0->dbt-snowflake)
[2023-08-04T18:12:36.236+0000] {subprocess.py:93} INFO -   Downloading jaraco.classes-3.2.3-py3-none-any.whl (6.0 kB)
[2023-08-04T18:12:36.240+0000] {subprocess.py:93} INFO - Requirement already satisfied: importlib-resources in /home/***/.local/lib/python3.7/site-packages (from keyring!=16.1.0,<24.0.0->snowflake-connector-python[secure-local-storage]~=3.0->dbt-snowflake) (5.10.0)
[2023-08-04T18:12:36.261+0000] {subprocess.py:93} INFO - Collecting SecretStorage>=3.2 (from keyring!=16.1.0,<24.0.0->snowflake-connector-python[secure-local-storage]~=3.0->dbt-snowflake)
[2023-08-04T18:12:36.288+0000] {subprocess.py:93} INFO -   Downloading SecretStorage-3.3.3-py3-none-any.whl (15 kB)
[2023-08-04T18:12:36.328+0000] {subprocess.py:93} INFO - Collecting jeepney>=0.4.2 (from keyring!=16.1.0,<24.0.0->snowflake-connector-python[secure-local-storage]~=3.0->dbt-snowflake)
[2023-08-04T18:12:36.346+0000] {subprocess.py:93} INFO -   Downloading jeepney-0.8.0-py3-none-any.whl (48 kB)
[2023-08-04T18:12:36.351+0000] {subprocess.py:93} INFO -      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.4/48.4 kB 13.7 MB/s eta 0:00:00
[2023-08-04T18:12:36.370+0000] {subprocess.py:93} INFO - Requirement already satisfied: zipp>=0.5 in /home/***/.local/lib/python3.7/site-packages (from importlib-metadata->snowflake-connector-python[secure-local-storage]~=3.0->dbt-snowflake) (3.11.0)
[2023-08-04T18:12:36.400+0000] {subprocess.py:93} INFO - Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /home/***/.local/lib/python3.7/site-packages (from packaging>20.9->dbt-core~=1.5.0->dbt-snowflake) (3.0.9)
[2023-08-04T18:12:36.494+0000] {subprocess.py:93} INFO - Requirement already satisfied: attrs>=17.4.0 in /home/***/.local/lib/python3.7/site-packages (from jsonschema>=3.0->hologram<=0.0.16,>=0.0.14->dbt-core~=1.5.0->dbt-snowflake) (22.1.0)
[2023-08-04T18:12:36.496+0000] {subprocess.py:93} INFO - Requirement already satisfied: pkgutil-resolve-name>=1.3.10 in /home/***/.local/lib/python3.7/site-packages (from jsonschema>=3.0->hologram<=0.0.16,>=0.0.14->dbt-core~=1.5.0->dbt-snowflake) (1.3.10)
[2023-08-04T18:12:36.497+0000] {subprocess.py:93} INFO - Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in /home/***/.local/lib/python3.7/site-packages (from jsonschema>=3.0->hologram<=0.0.16,>=0.0.14->dbt-core~=1.5.0->dbt-snowflake) (0.19.2)
[2023-08-04T18:12:36.533+0000] {subprocess.py:93} INFO - Requirement already satisfied: future in /home/***/.local/lib/python3.7/site-packages (from parsedatetime!=2.5,!=2.6,>=2.1->agate<1.7.1,>=1.6->dbt-core~=1.5.0->dbt-snowflake) (0.18.2)
[2023-08-04T18:12:36.551+0000] {subprocess.py:93} INFO - Requirement already satisfied: text-unidecode>=1.3 in /home/***/.local/lib/python3.7/site-packages (from python-slugify>=1.2.1->agate<1.7.1,>=1.6->dbt-core~=1.5.0->dbt-snowflake) (1.3)
[2023-08-04T18:12:36.632+0000] {subprocess.py:93} INFO - Collecting more-itertools (from jaraco.classes->keyring!=16.1.0,<24.0.0->snowflake-connector-python[secure-local-storage]~=3.0->dbt-snowflake)
[2023-08-04T18:12:36.687+0000] {subprocess.py:93} INFO -   Downloading more_itertools-9.1.0-py3-none-any.whl (54 kB)
[2023-08-04T18:12:36.704+0000] {subprocess.py:93} INFO -      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 54.2/54.2 kB 3.4 MB/s eta 0:00:00
[2023-08-04T18:12:36.802+0000] {subprocess.py:93} INFO - Building wheels for collected packages: minimal-snowplow-tracker, logbook, parsedatetime
[2023-08-04T18:12:36.803+0000] {subprocess.py:93} INFO -   Building wheel for minimal-snowplow-tracker (setup.py): started
[2023-08-04T18:12:37.494+0000] {subprocess.py:93} INFO -   Building wheel for minimal-snowplow-tracker (setup.py): finished with status 'done'
[2023-08-04T18:12:37.496+0000] {subprocess.py:93} INFO -   Created wheel for minimal-snowplow-tracker: filename=minimal_snowplow_tracker-0.0.2-py3-none-any.whl size=17815 sha256=ff1c92868c57c4651ca4f04e89508c23edf822521acc3ca725cd3d678af6018a
[2023-08-04T18:12:37.497+0000] {subprocess.py:93} INFO -   Stored in directory: /home/***/.cache/pip/wheels/9d/ee/55/8faefee41ca3bccb25152e0159002567575047be7ef1ce8ac1
[2023-08-04T18:12:37.499+0000] {subprocess.py:93} INFO -   Building wheel for logbook (setup.py): started
[2023-08-04T18:12:38.207+0000] {subprocess.py:93} INFO -   Building wheel for logbook (setup.py): finished with status 'done'
[2023-08-04T18:12:38.209+0000] {subprocess.py:93} INFO -   Created wheel for logbook: filename=Logbook-1.5.3-cp37-cp37m-linux_aarch64.whl size=66398 sha256=0a4565b5c450e95f4b1e2c90a5fd7bb43ec0979b4a6ce9ac9ef00891eb9994ba
[2023-08-04T18:12:38.210+0000] {subprocess.py:93} INFO -   Stored in directory: /home/***/.cache/pip/wheels/95/4b/a3/fc9b9d17a06a956767a8dc74058ba64d4306653df2289094cc
[2023-08-04T18:12:38.212+0000] {subprocess.py:93} INFO -   Building wheel for parsedatetime (setup.py): started
[2023-08-04T18:12:38.796+0000] {subprocess.py:93} INFO -   Building wheel for parsedatetime (setup.py): finished with status 'done'
[2023-08-04T18:12:38.801+0000] {subprocess.py:93} INFO -   Created wheel for parsedatetime: filename=parsedatetime-2.4-py3-none-any.whl size=42773 sha256=99d72ff6b037363928e357d0c92e693358447f3a50692a27be23baa0b9136909
[2023-08-04T18:12:38.804+0000] {subprocess.py:93} INFO -   Stored in directory: /home/***/.cache/pip/wheels/68/0f/b7/539a31a4068565a53913d7f8cfc6c7521cca2ea091b8a72048
[2023-08-04T18:12:38.805+0000] {subprocess.py:93} INFO - Successfully built minimal-snowplow-tracker logbook parsedatetime
[2023-08-04T18:12:41.153+0000] {subprocess.py:93} INFO - Installing collected packages: pytimeparse, logbook, pyyaml, protobuf, parsedatetime, networkx, more-itertools, mashumaro, leather, jeepney, dbt-extractor, minimal-snowplow-tracker, jaraco.classes, agate, SecretStorage, hologram, keyring, dbt-core, dbt-snowflake
[2023-08-04T18:12:41.193+0000] {subprocess.py:93} INFO -   Attempting uninstall: pyyaml
[2023-08-04T18:12:41.194+0000] {subprocess.py:93} INFO -     Found existing installation: PyYAML 5.4.1
[2023-08-04T18:12:41.199+0000] {subprocess.py:93} INFO -     Uninstalling PyYAML-5.4.1:
[2023-08-04T18:12:41.222+0000] {subprocess.py:93} INFO -       Successfully uninstalled PyYAML-5.4.1
[2023-08-04T18:12:41.262+0000] {subprocess.py:93} INFO -   Attempting uninstall: protobuf
[2023-08-04T18:12:41.264+0000] {subprocess.py:93} INFO -     Found existing installation: protobuf 3.20.0
[2023-08-04T18:12:41.274+0000] {subprocess.py:93} INFO -     Uninstalling protobuf-3.20.0:
[2023-08-04T18:12:42.214+0000] {subprocess.py:93} INFO -       Successfully uninstalled protobuf-3.20.0
[2023-08-04T18:12:43.485+0000] {subprocess.py:93} INFO - ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
[2023-08-04T18:12:43.488+0000] {subprocess.py:93} INFO - apache-***-providers-google 8.6.0 requires protobuf<=3.20.0, but you have protobuf 4.23.4 which is incompatible.
[2023-08-04T18:12:43.490+0000] {subprocess.py:93} INFO - awscli 1.27.156 requires PyYAML<5.5,>=3.10, but you have pyyaml 6.0.1 which is incompatible.
[2023-08-04T18:12:43.491+0000] {subprocess.py:93} INFO - google-ads 18.0.0 requires protobuf!=3.18.*,!=3.19.*,<=3.20.0,>=3.12.0, but you have protobuf 4.23.4 which is incompatible.
[2023-08-04T18:12:43.492+0000] {subprocess.py:93} INFO - google-cloud-aiplatform 1.16.1 requires protobuf<4.0.0dev,>=3.19.0, but you have protobuf 4.23.4 which is incompatible.
[2023-08-04T18:12:43.493+0000] {subprocess.py:93} INFO - google-cloud-appengine-logging 1.1.3 requires protobuf<4.0.0dev,>=3.19.0, but you have protobuf 4.23.4 which is incompatible.
[2023-08-04T18:12:43.495+0000] {subprocess.py:93} INFO - google-cloud-automl 2.8.0 requires protobuf<4.0.0dev,>=3.19.0, but you have protobuf 4.23.4 which is incompatible.
[2023-08-04T18:12:43.496+0000] {subprocess.py:93} INFO - google-cloud-bigquery 2.34.4 requires protobuf<4.0.0dev,>=3.12.0, but you have protobuf 4.23.4 which is incompatible.
[2023-08-04T18:12:43.497+0000] {subprocess.py:93} INFO - google-cloud-bigquery-datatransfer 3.7.0 requires protobuf<4.0.0dev,>=3.19.0, but you have protobuf 4.23.4 which is incompatible.
[2023-08-04T18:12:43.505+0000] {subprocess.py:93} INFO - google-cloud-bigquery-storage 2.14.1 requires protobuf<4.0.0dev,>=3.19.0, but you have protobuf 4.23.4 which is incompatible.
[2023-08-04T18:12:43.506+0000] {subprocess.py:93} INFO - google-cloud-bigtable 1.7.3 requires protobuf<4.0.0dev, but you have protobuf 4.23.4 which is incompatible.
[2023-08-04T18:12:43.507+0000] {subprocess.py:93} INFO - google-cloud-build 3.9.0 requires protobuf<4.0.0dev,>=3.19.0, but you have protobuf 4.23.4 which is incompatible.
[2023-08-04T18:12:43.508+0000] {subprocess.py:93} INFO - google-cloud-container 2.11.1 requires protobuf<4.0.0dev,>=3.19.0, but you have protobuf 4.23.4 which is incompatible.
[2023-08-04T18:12:43.510+0000] {subprocess.py:93} INFO - google-cloud-datacatalog 3.9.0 requires protobuf<4.0.0dev,>=3.19.0, but you have protobuf 4.23.4 which is incompatible.
[2023-08-04T18:12:43.511+0000] {subprocess.py:93} INFO - google-cloud-dataform 0.2.0 requires protobuf<4.0.0dev,>=3.19.0, but you have protobuf 4.23.4 which is incompatible.
[2023-08-04T18:12:43.512+0000] {subprocess.py:93} INFO - google-cloud-dataplex 1.1.0 requires protobuf<4.0.0dev,>=3.19.0, but you have protobuf 4.23.4 which is incompatible.
[2023-08-04T18:12:43.513+0000] {subprocess.py:93} INFO - google-cloud-dataproc 5.0.0 requires protobuf<4.0.0dev,>=3.19.0, but you have protobuf 4.23.4 which is incompatible.
[2023-08-04T18:12:43.523+0000] {subprocess.py:93} INFO - google-cloud-dataproc-metastore 1.6.0 requires protobuf<4.0.0dev,>=3.19.0, but you have protobuf 4.23.4 which is incompatible.
[2023-08-04T18:12:43.523+0000] {subprocess.py:93} INFO - google-cloud-dlp 1.0.2 requires protobuf<4.0.0dev, but you have protobuf 4.23.4 which is incompatible.
[2023-08-04T18:12:43.525+0000] {subprocess.py:93} INFO - google-cloud-kms 2.12.0 requires protobuf<4.0.0dev,>=3.19.0, but you have protobuf 4.23.4 which is incompatible.
[2023-08-04T18:12:43.526+0000] {subprocess.py:93} INFO - google-cloud-language 1.3.2 requires protobuf<4.0.0dev, but you have protobuf 4.23.4 which is incompatible.
[2023-08-04T18:12:43.528+0000] {subprocess.py:93} INFO - google-cloud-logging 3.2.1 requires protobuf<4.0.0dev,>=3.19.0, but you have protobuf 4.23.4 which is incompatible.
[2023-08-04T18:12:43.529+0000] {subprocess.py:93} INFO - google-cloud-memcache 1.4.1 requires protobuf<4.0.0dev,>=3.19.0, but you have protobuf 4.23.4 which is incompatible.
[2023-08-04T18:12:43.530+0000] {subprocess.py:93} INFO - google-cloud-monitoring 2.11.0 requires protobuf<4.0.0dev,>=3.19.0, but you have protobuf 4.23.4 which is incompatible.
[2023-08-04T18:12:43.531+0000] {subprocess.py:93} INFO - google-cloud-orchestration-*** 1.4.1 requires protobuf<4.0.0dev,>=3.19.0, but you have protobuf 4.23.4 which is incompatible.
[2023-08-04T18:12:43.541+0000] {subprocess.py:93} INFO - google-cloud-os-login 2.7.1 requires protobuf<4.0.0dev,>=3.19.0, but you have protobuf 4.23.4 which is incompatible.
[2023-08-04T18:12:43.543+0000] {subprocess.py:93} INFO - google-cloud-pubsub 2.13.5 requires protobuf<4.0.0dev,>=3.19.0, but you have protobuf 4.23.4 which is incompatible.
[2023-08-04T18:12:43.544+0000] {subprocess.py:93} INFO - google-cloud-redis 2.9.0 requires protobuf<4.0.0dev,>=3.19.0, but you have protobuf 4.23.4 which is incompatible.
[2023-08-04T18:12:43.545+0000] {subprocess.py:93} INFO - google-cloud-resource-manager 1.6.0 requires protobuf<4.0.0dev,>=3.19.0, but you have protobuf 4.23.4 which is incompatible.
[2023-08-04T18:12:43.546+0000] {subprocess.py:93} INFO - google-cloud-secret-manager 1.0.2 requires protobuf<4.0.0dev, but you have protobuf 4.23.4 which is incompatible.
[2023-08-04T18:12:43.547+0000] {subprocess.py:93} INFO - google-cloud-spanner 1.19.3 requires protobuf<4.0.0dev, but you have protobuf 4.23.4 which is incompatible.
[2023-08-04T18:12:43.549+0000] {subprocess.py:93} INFO - google-cloud-speech 1.3.4 requires protobuf<4.0.0dev, but you have protobuf 4.23.4 which is incompatible.
[2023-08-04T18:12:43.550+0000] {subprocess.py:93} INFO - google-cloud-tasks 2.10.1 requires protobuf<4.0.0dev,>=3.19.0, but you have protobuf 4.23.4 which is incompatible.
[2023-08-04T18:12:43.551+0000] {subprocess.py:93} INFO - google-cloud-texttospeech 1.0.3 requires protobuf<4.0.0dev, but you have protobuf 4.23.4 which is incompatible.
[2023-08-04T18:12:43.552+0000] {subprocess.py:93} INFO - google-cloud-translate 1.7.2 requires protobuf<4.0.0dev, but you have protobuf 4.23.4 which is incompatible.
[2023-08-04T18:12:43.553+0000] {subprocess.py:93} INFO - google-cloud-videointelligence 1.16.3 requires protobuf<4.0.0dev, but you have protobuf 4.23.4 which is incompatible.
[2023-08-04T18:12:43.554+0000] {subprocess.py:93} INFO - google-cloud-vision 1.0.2 requires protobuf<4.0.0dev, but you have protobuf 4.23.4 which is incompatible.
[2023-08-04T18:12:43.555+0000] {subprocess.py:93} INFO - google-cloud-workflows 1.7.1 requires protobuf<4.0.0dev,>=3.19.0, but you have protobuf 4.23.4 which is incompatible.
[2023-08-04T18:12:43.556+0000] {subprocess.py:93} INFO - Successfully installed SecretStorage-3.3.3 agate-1.7.0 dbt-core-1.5.4 dbt-extractor-0.4.1 dbt-snowflake-1.5.1 hologram-0.0.16 jaraco.classes-3.2.3 jeepney-0.8.0 keyring-23.13.1 leather-0.3.4 logbook-1.5.3 mashumaro-3.6 minimal-snowplow-tracker-0.0.2 more-itertools-9.1.0 networkx-2.6.3 parsedatetime-2.4 protobuf-4.23.4 pytimeparse-1.1.8 pyyaml-6.0.1
[2023-08-04T18:12:43.607+0000] {subprocess.py:93} INFO - 
[2023-08-04T18:12:43.612+0000] {subprocess.py:93} INFO - [notice] A new release of pip is available: 23.1.2 -> 23.2.1
[2023-08-04T18:12:43.651+0000] {subprocess.py:93} INFO - [notice] To update, run: python -m pip install --upgrade pip
[2023-08-04T18:12:45.253+0000] {subprocess.py:93} INFO - [0m18:12:45  Running with dbt=1.5.4
[2023-08-04T18:12:45.732+0000] {subprocess.py:93} INFO - [0m18:12:45  Registered adapter: snowflake=1.5.1
[2023-08-04T18:12:45.798+0000] {subprocess.py:93} INFO - [0m18:12:45  Unable to do partial parsing because of a version mismatch
[2023-08-04T18:12:46.746+0000] {subprocess.py:93} INFO - [0m18:12:46  Found 12 models, 2 tests, 0 snapshots, 0 analyses, 322 macros, 0 operations, 0 seed files, 0 sources, 0 exposures, 0 metrics, 0 groups
[2023-08-04T18:12:46.752+0000] {subprocess.py:93} INFO - [0m18:12:46
[2023-08-04T18:12:48.540+0000] {subprocess.py:93} INFO - [0m18:12:48  Concurrency: 4 threads (target='dev')
[2023-08-04T18:12:48.553+0000] {subprocess.py:93} INFO - [0m18:12:48
[2023-08-04T18:12:48.565+0000] {subprocess.py:93} INFO - [0m18:12:48  1 of 1 START sql table model DBT_POC.stg_ipflow_input_data ..................... [RUN]
[2023-08-04T18:12:49.436+0000] {subprocess.py:93} INFO - [0m18:12:49  1 of 1 ERROR creating sql table model DBT_POC.stg_ipflow_input_data ............ [[31mERROR[0m in 0.85s]
[2023-08-04T18:12:49.486+0000] {subprocess.py:93} INFO - [0m18:12:49
[2023-08-04T18:12:49.492+0000] {subprocess.py:93} INFO - [0m18:12:49  Finished running 1 table model in 0 hours 0 minutes and 2.73 seconds (2.73s).
[2023-08-04T18:12:49.683+0000] {subprocess.py:93} INFO - [0m18:12:49
[2023-08-04T18:12:49.687+0000] {subprocess.py:93} INFO - [0m18:12:49  [31mCompleted with 1 error and 0 warnings:[0m
[2023-08-04T18:12:49.689+0000] {subprocess.py:93} INFO - [0m18:12:49
[2023-08-04T18:12:49.692+0000] {subprocess.py:93} INFO - [0m18:12:49  [33mDatabase Error in model stg_ipflow_input_data (models/ipflow/stg_ipflow_input_data.sql)[0m
[2023-08-04T18:12:49.695+0000] {subprocess.py:93} INFO - [0m18:12:49    002003 (42S02): SQL compilation error:
[2023-08-04T18:12:49.699+0000] {subprocess.py:93} INFO - [0m18:12:49    Object 'FIVE_BY_FIVE_DEMO.PRODUCTS.IP_COMPANY_2_10_0' does not exist or not authorized.
[2023-08-04T18:12:49.704+0000] {subprocess.py:93} INFO - [0m18:12:49    compiled Code at target/run/dbt_dsg_app/models/ipflow/stg_ipflow_input_data.sql
[2023-08-04T18:12:49.712+0000] {subprocess.py:93} INFO - [0m18:12:49
[2023-08-04T18:12:49.716+0000] {subprocess.py:93} INFO - [0m18:12:49  Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1
[2023-08-04T18:12:50.543+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-08-04T18:12:50.618+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-08-04T18:12:50.635+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=dbt_ipflow_dag, task_id=get_input_data, execution_date=20230803T000000, start_date=20230804T181231, end_date=20230804T181250
[2023-08-04T18:12:50.675+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 4 for task get_input_data (Bash command failed. The command returned a non-zero exit code 1.; 246)
[2023-08-04T18:12:50.756+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-08-04T18:12:50.794+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
