[2023-08-04T00:00:01.212+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: dbt_ipflow_dag.get_input_data scheduled__2023-08-03T00:00:00+00:00 [queued]>
[2023-08-04T00:00:01.220+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: dbt_ipflow_dag.get_input_data scheduled__2023-08-03T00:00:00+00:00 [queued]>
[2023-08-04T00:00:01.221+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-08-04T00:00:01.222+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2023-08-04T00:00:01.223+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-08-04T00:00:01.233+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): get_input_data> on 2023-08-03 00:00:00+00:00
[2023-08-04T00:00:01.239+0000] {standard_task_runner.py:55} INFO - Started process 96572 to run task
[2023-08-04T00:00:01.244+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dbt_ipflow_dag', 'get_input_data', 'scheduled__2023-08-03T00:00:00+00:00', '--job-id', '100', '--raw', '--subdir', 'DAGS_FOLDER/dbt_ip_flow_dag.py', '--cfg-path', '/tmp/tmp6zjoqadm']
[2023-08-04T00:00:01.268+0000] {standard_task_runner.py:83} INFO - Job 100: Subtask get_input_data
[2023-08-04T00:00:01.337+0000] {task_command.py:389} INFO - Running <TaskInstance: dbt_ipflow_dag.get_input_data scheduled__2023-08-03T00:00:00+00:00 [running]> on host 635f1a4ac995
[2023-08-04T00:00:01.395+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dbt_ipflow_dag
AIRFLOW_CTX_TASK_ID=get_input_data
AIRFLOW_CTX_EXECUTION_DATE=2023-08-03T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-08-03T00:00:00+00:00
[2023-08-04T00:00:01.399+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-08-04T00:00:01.400+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', "dbt run --select stg_ipflow_input_data --profiles-dir /opt/***/dbt/dbt_dsg_app --project-dir /opt/***/dbt/dbt_dsg_app  --target dev --vars '{'env': 'dev'}' "]
[2023-08-04T00:00:01.415+0000] {subprocess.py:86} INFO - Output:
[2023-08-04T00:00:02.779+0000] {subprocess.py:93} INFO - [0m00:00:02  Running with dbt=1.5.1
[2023-08-04T00:00:03.459+0000] {subprocess.py:93} INFO - [0m00:00:03  Found 12 models, 2 tests, 0 snapshots, 0 analyses, 321 macros, 0 operations, 0 seed files, 0 sources, 0 exposures, 0 metrics, 0 groups
[2023-08-04T00:00:03.467+0000] {subprocess.py:93} INFO - [0m00:00:03
[2023-08-04T00:00:03.935+0000] {subprocess.py:93} INFO - [0m00:00:03
[2023-08-04T00:00:03.937+0000] {subprocess.py:93} INFO - [0m00:00:03  Finished running  in 0 hours 0 minutes and 0.46 seconds (0.46s).
[2023-08-04T00:00:03.940+0000] {subprocess.py:93} INFO - [0m00:00:03  Encountered an error:
[2023-08-04T00:00:03.941+0000] {subprocess.py:93} INFO - Runtime Error
[2023-08-04T00:00:03.942+0000] {subprocess.py:93} INFO -   Database error while listing schemas in database "DEV_QA"
[2023-08-04T00:00:03.944+0000] {subprocess.py:93} INFO -   Database Error
[2023-08-04T00:00:03.945+0000] {subprocess.py:93} INFO -     250001 (08001): Failed to connect to DB: bcb55215.us-east-1.snowflakecomputing.com:443. Incorrect username or password was specified.
[2023-08-04T00:00:04.667+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-08-04T00:00:04.683+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-08-04T00:00:04.688+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=dbt_ipflow_dag, task_id=get_input_data, execution_date=20230803T000000, start_date=20230804T000001, end_date=20230804T000004
[2023-08-04T00:00:04.701+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 100 for task get_input_data (Bash command failed. The command returned a non-zero exit code 2.; 96572)
[2023-08-04T00:00:04.751+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-08-04T00:00:04.776+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-08-04T16:22:43.872+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: dbt_ipflow_dag.get_input_data scheduled__2023-08-03T00:00:00+00:00 [queued]>
[2023-08-04T16:22:43.886+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: dbt_ipflow_dag.get_input_data scheduled__2023-08-03T00:00:00+00:00 [queued]>
[2023-08-04T16:22:43.888+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-08-04T16:22:43.890+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2023-08-04T16:22:43.892+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-08-04T16:22:43.902+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): get_input_data> on 2023-08-03 00:00:00+00:00
[2023-08-04T16:22:43.911+0000] {standard_task_runner.py:55} INFO - Started process 187 to run task
[2023-08-04T16:22:43.915+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dbt_ipflow_dag', 'get_input_data', 'scheduled__2023-08-03T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/dbt_ip_flow_dag.py', '--cfg-path', '/tmp/tmpxk6s1fto']
[2023-08-04T16:22:43.919+0000] {standard_task_runner.py:83} INFO - Job 3: Subtask get_input_data
[2023-08-04T16:22:43.988+0000] {task_command.py:389} INFO - Running <TaskInstance: dbt_ipflow_dag.get_input_data scheduled__2023-08-03T00:00:00+00:00 [running]> on host 68b6c38d20d3
[2023-08-04T16:22:44.059+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dbt_ipflow_dag
AIRFLOW_CTX_TASK_ID=get_input_data
AIRFLOW_CTX_EXECUTION_DATE=2023-08-03T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-08-03T00:00:00+00:00
[2023-08-04T16:22:44.066+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-08-04T16:22:44.067+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', "dbt run --select stg_ipflow_input_data --profiles-dir /opt/***/dbt/dbt_dsg_app --project-dir /opt/***/dbt/dbt_dsg_app  --target dev --vars '{'env': 'dev'}' "]
[2023-08-04T16:22:44.093+0000] {subprocess.py:86} INFO - Output:
[2023-08-04T16:22:44.098+0000] {subprocess.py:93} INFO - /bin/bash: line 1: dbt: command not found
[2023-08-04T16:22:44.100+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2023-08-04T16:22:44.120+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-08-04T16:22:44.128+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=dbt_ipflow_dag, task_id=get_input_data, execution_date=20230803T000000, start_date=20230804T162243, end_date=20230804T162244
[2023-08-04T16:22:44.196+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 3 for task get_input_data (Bash command failed. The command returned a non-zero exit code 127.; 187)
[2023-08-04T16:22:44.250+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-08-04T16:22:44.294+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-08-04T16:51:03.184+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: dbt_ipflow_dag.get_input_data scheduled__2023-08-03T00:00:00+00:00 [queued]>
[2023-08-04T16:51:03.231+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: dbt_ipflow_dag.get_input_data scheduled__2023-08-03T00:00:00+00:00 [queued]>
[2023-08-04T16:51:03.232+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-08-04T16:51:03.233+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2023-08-04T16:51:03.235+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-08-04T16:51:03.244+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): get_input_data> on 2023-08-03 00:00:00+00:00
[2023-08-04T16:51:03.253+0000] {standard_task_runner.py:55} INFO - Started process 98 to run task
[2023-08-04T16:51:03.258+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dbt_ipflow_dag', 'get_input_data', 'scheduled__2023-08-03T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/dbt_ip_flow_dag.py', '--cfg-path', '/tmp/tmpwpmnx6ni']
[2023-08-04T16:51:03.261+0000] {standard_task_runner.py:83} INFO - Job 3: Subtask get_input_data
[2023-08-04T16:51:03.333+0000] {task_command.py:389} INFO - Running <TaskInstance: dbt_ipflow_dag.get_input_data scheduled__2023-08-03T00:00:00+00:00 [running]> on host 0d96cb4655e5
[2023-08-04T16:51:03.400+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dbt_ipflow_dag
AIRFLOW_CTX_TASK_ID=get_input_data
AIRFLOW_CTX_EXECUTION_DATE=2023-08-03T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-08-03T00:00:00+00:00
[2023-08-04T16:51:03.403+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-08-04T16:51:03.405+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', "dbt run --select stg_ipflow_input_data --profiles-dir /opt/***/dbt/dbt_dsg_app --project-dir /opt/***/dbt/dbt_dsg_app  --target dev --vars '{'env': 'dev'}' "]
[2023-08-04T16:51:03.427+0000] {subprocess.py:86} INFO - Output:
[2023-08-04T16:51:03.429+0000] {subprocess.py:93} INFO - /bin/bash: line 1: dbt: command not found
[2023-08-04T16:51:03.431+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2023-08-04T16:51:03.447+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-08-04T16:51:03.454+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=dbt_ipflow_dag, task_id=get_input_data, execution_date=20230803T000000, start_date=20230804T165103, end_date=20230804T165103
[2023-08-04T16:51:03.477+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 3 for task get_input_data (Bash command failed. The command returned a non-zero exit code 127.; 98)
[2023-08-04T16:51:03.511+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-08-04T16:51:03.534+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-08-04T16:56:09.255+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: dbt_ipflow_dag.get_input_data scheduled__2023-08-03T00:00:00+00:00 [queued]>
[2023-08-04T16:56:09.263+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: dbt_ipflow_dag.get_input_data scheduled__2023-08-03T00:00:00+00:00 [queued]>
[2023-08-04T16:56:09.264+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-08-04T16:56:09.265+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2023-08-04T16:56:09.266+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-08-04T16:56:09.274+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): get_input_data> on 2023-08-03 00:00:00+00:00
[2023-08-04T16:56:09.282+0000] {standard_task_runner.py:55} INFO - Started process 89 to run task
[2023-08-04T16:56:09.286+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dbt_ipflow_dag', 'get_input_data', 'scheduled__2023-08-03T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/dbt_ip_flow_dag.py', '--cfg-path', '/tmp/tmps1cj1v71']
[2023-08-04T16:56:09.294+0000] {standard_task_runner.py:83} INFO - Job 3: Subtask get_input_data
[2023-08-04T16:56:09.360+0000] {task_command.py:389} INFO - Running <TaskInstance: dbt_ipflow_dag.get_input_data scheduled__2023-08-03T00:00:00+00:00 [running]> on host bd637bacfe6d
[2023-08-04T16:56:09.421+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dbt_ipflow_dag
AIRFLOW_CTX_TASK_ID=get_input_data
AIRFLOW_CTX_EXECUTION_DATE=2023-08-03T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-08-03T00:00:00+00:00
[2023-08-04T16:56:09.427+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-08-04T16:56:09.429+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', "dbt run --select stg_ipflow_input_data --profiles-dir /opt/***/dbt/dbt_dsg_app --project-dir /opt/***/dbt/dbt_dsg_app  --target dev --vars '{'env': 'dev'}' "]
[2023-08-04T16:56:09.442+0000] {subprocess.py:86} INFO - Output:
[2023-08-04T16:56:09.444+0000] {subprocess.py:93} INFO - /bin/bash: line 1: dbt: command not found
[2023-08-04T16:56:09.445+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2023-08-04T16:56:09.458+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-08-04T16:56:09.462+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=dbt_ipflow_dag, task_id=get_input_data, execution_date=20230803T000000, start_date=20230804T165609, end_date=20230804T165609
[2023-08-04T16:56:09.473+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 3 for task get_input_data (Bash command failed. The command returned a non-zero exit code 127.; 89)
[2023-08-04T16:56:09.509+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-08-04T16:56:09.535+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-08-04T17:20:08.049+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: dbt_ipflow_dag.get_input_data scheduled__2023-08-03T00:00:00+00:00 [queued]>
[2023-08-04T17:20:08.057+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: dbt_ipflow_dag.get_input_data scheduled__2023-08-03T00:00:00+00:00 [queued]>
[2023-08-04T17:20:08.058+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-08-04T17:20:08.059+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2023-08-04T17:20:08.068+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-08-04T17:20:08.077+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): get_input_data> on 2023-08-03 00:00:00+00:00
[2023-08-04T17:20:08.084+0000] {standard_task_runner.py:55} INFO - Started process 138 to run task
[2023-08-04T17:20:08.089+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dbt_ipflow_dag', 'get_input_data', 'scheduled__2023-08-03T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/dbt_ip_flow_dag.py', '--cfg-path', '/tmp/tmpgqlnb61b']
[2023-08-04T17:20:08.092+0000] {standard_task_runner.py:83} INFO - Job 3: Subtask get_input_data
[2023-08-04T17:20:08.158+0000] {task_command.py:389} INFO - Running <TaskInstance: dbt_ipflow_dag.get_input_data scheduled__2023-08-03T00:00:00+00:00 [running]> on host 40a01812b2dd
[2023-08-04T17:20:08.215+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dbt_ipflow_dag
AIRFLOW_CTX_TASK_ID=get_input_data
AIRFLOW_CTX_EXECUTION_DATE=2023-08-03T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-08-03T00:00:00+00:00
[2023-08-04T17:20:08.220+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-08-04T17:20:08.224+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', "dbt run --select stg_ipflow_input_data --profiles-dir /opt/***/dbt/dbt_dsg_app --project-dir /opt/***/dbt/dbt_dsg_app  --target dev --vars '{'env': 'dev'}' "]
[2023-08-04T17:20:08.239+0000] {subprocess.py:86} INFO - Output:
[2023-08-04T17:20:08.241+0000] {subprocess.py:93} INFO - /bin/bash: line 1: dbt: command not found
[2023-08-04T17:20:08.243+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2023-08-04T17:20:08.256+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-08-04T17:20:08.260+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=dbt_ipflow_dag, task_id=get_input_data, execution_date=20230803T000000, start_date=20230804T172008, end_date=20230804T172008
[2023-08-04T17:20:08.271+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 3 for task get_input_data (Bash command failed. The command returned a non-zero exit code 127.; 138)
[2023-08-04T17:20:08.300+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-08-04T17:20:08.316+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-08-04T17:24:05.755+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: dbt_ipflow_dag.get_input_data scheduled__2023-08-03T00:00:00+00:00 [queued]>
[2023-08-04T17:24:05.763+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: dbt_ipflow_dag.get_input_data scheduled__2023-08-03T00:00:00+00:00 [queued]>
[2023-08-04T17:24:05.764+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-08-04T17:24:05.766+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2023-08-04T17:24:05.767+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-08-04T17:24:05.775+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): get_input_data> on 2023-08-03 00:00:00+00:00
[2023-08-04T17:24:05.783+0000] {standard_task_runner.py:55} INFO - Started process 102 to run task
[2023-08-04T17:24:05.788+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dbt_ipflow_dag', 'get_input_data', 'scheduled__2023-08-03T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/dbt_ip_flow_dag.py', '--cfg-path', '/tmp/tmppdafcoxy']
[2023-08-04T17:24:05.792+0000] {standard_task_runner.py:83} INFO - Job 3: Subtask get_input_data
[2023-08-04T17:24:05.881+0000] {task_command.py:389} INFO - Running <TaskInstance: dbt_ipflow_dag.get_input_data scheduled__2023-08-03T00:00:00+00:00 [running]> on host e6719fd6f95b
[2023-08-04T17:24:05.947+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dbt_ipflow_dag
AIRFLOW_CTX_TASK_ID=get_input_data
AIRFLOW_CTX_EXECUTION_DATE=2023-08-03T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-08-03T00:00:00+00:00
[2023-08-04T17:24:05.951+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-08-04T17:24:05.953+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', "dbt run --select stg_ipflow_input_data --profiles-dir /opt/***/dbt/dbt_dsg_app --project-dir /opt/***/dbt/dbt_dsg_app  --target dev --vars '{'env': 'dev'}' "]
[2023-08-04T17:24:05.979+0000] {subprocess.py:86} INFO - Output:
[2023-08-04T17:24:05.982+0000] {subprocess.py:93} INFO - /bin/bash: line 1: dbt: command not found
[2023-08-04T17:24:05.983+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2023-08-04T17:24:05.997+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-08-04T17:24:06.001+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=dbt_ipflow_dag, task_id=get_input_data, execution_date=20230803T000000, start_date=20230804T172405, end_date=20230804T172406
[2023-08-04T17:24:06.012+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 3 for task get_input_data (Bash command failed. The command returned a non-zero exit code 127.; 102)
[2023-08-04T17:24:06.040+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-08-04T17:24:06.060+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-08-04T17:34:49.882+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: dbt_ipflow_dag.get_input_data scheduled__2023-08-03T00:00:00+00:00 [queued]>
[2023-08-04T17:34:49.890+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: dbt_ipflow_dag.get_input_data scheduled__2023-08-03T00:00:00+00:00 [queued]>
[2023-08-04T17:34:49.891+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-08-04T17:34:49.892+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2023-08-04T17:34:49.925+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-08-04T17:34:49.935+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): get_input_data> on 2023-08-03 00:00:00+00:00
[2023-08-04T17:34:49.942+0000] {standard_task_runner.py:55} INFO - Started process 125 to run task
[2023-08-04T17:34:49.946+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dbt_ipflow_dag', 'get_input_data', 'scheduled__2023-08-03T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/dbt_ip_flow_dag.py', '--cfg-path', '/tmp/tmpvnvuqe_p']
[2023-08-04T17:34:49.950+0000] {standard_task_runner.py:83} INFO - Job 3: Subtask get_input_data
[2023-08-04T17:34:50.013+0000] {task_command.py:389} INFO - Running <TaskInstance: dbt_ipflow_dag.get_input_data scheduled__2023-08-03T00:00:00+00:00 [running]> on host 9817f6d599e1
[2023-08-04T17:34:50.070+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dbt_ipflow_dag
AIRFLOW_CTX_TASK_ID=get_input_data
AIRFLOW_CTX_EXECUTION_DATE=2023-08-03T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-08-03T00:00:00+00:00
[2023-08-04T17:34:50.075+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-08-04T17:34:50.076+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', "dbt run --select stg_ipflow_input_data --profiles-dir /opt/***/dbt/dbt_dsg_app --project-dir /opt/***/dbt/dbt_dsg_app  --target dev --vars '{'env': 'dev'}' "]
[2023-08-04T17:34:50.097+0000] {subprocess.py:86} INFO - Output:
[2023-08-04T17:34:50.100+0000] {subprocess.py:93} INFO - /bin/bash: line 1: dbt: command not found
[2023-08-04T17:34:50.101+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2023-08-04T17:34:50.115+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-08-04T17:34:50.121+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=dbt_ipflow_dag, task_id=get_input_data, execution_date=20230803T000000, start_date=20230804T173449, end_date=20230804T173450
[2023-08-04T17:34:50.132+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 3 for task get_input_data (Bash command failed. The command returned a non-zero exit code 127.; 125)
[2023-08-04T17:34:50.162+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-08-04T17:34:50.187+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-08-04T17:44:25.742+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: dbt_ipflow_dag.get_input_data scheduled__2023-08-03T00:00:00+00:00 [queued]>
[2023-08-04T17:44:25.751+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: dbt_ipflow_dag.get_input_data scheduled__2023-08-03T00:00:00+00:00 [queued]>
[2023-08-04T17:44:25.752+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-08-04T17:44:25.753+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2023-08-04T17:44:25.755+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-08-04T17:44:25.765+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): get_input_data> on 2023-08-03 00:00:00+00:00
[2023-08-04T17:44:25.773+0000] {standard_task_runner.py:55} INFO - Started process 186 to run task
[2023-08-04T17:44:25.779+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dbt_ipflow_dag', 'get_input_data', 'scheduled__2023-08-03T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/dbt_ip_flow_dag.py', '--cfg-path', '/tmp/tmpc15zxpg2']
[2023-08-04T17:44:25.783+0000] {standard_task_runner.py:83} INFO - Job 3: Subtask get_input_data
[2023-08-04T17:44:25.872+0000] {task_command.py:389} INFO - Running <TaskInstance: dbt_ipflow_dag.get_input_data scheduled__2023-08-03T00:00:00+00:00 [running]> on host 1c85b9f3c91c
[2023-08-04T17:44:25.936+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dbt_ipflow_dag
AIRFLOW_CTX_TASK_ID=get_input_data
AIRFLOW_CTX_EXECUTION_DATE=2023-08-03T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-08-03T00:00:00+00:00
[2023-08-04T17:44:25.940+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-08-04T17:44:25.941+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', "source /tmp/dbt_venv/bin/activate && dbt run --select stg_ipflow_input_data --profiles-dir /opt/***/dbt/dbt_dsg_app --project-dir /opt/***/dbt/dbt_dsg_app  --target dev --vars '{'env': 'dev'}' "]
[2023-08-04T17:44:25.958+0000] {subprocess.py:86} INFO - Output:
[2023-08-04T17:44:25.961+0000] {subprocess.py:93} INFO - /bin/bash: line 1: /tmp/dbt_venv/bin/activate: No such file or directory
[2023-08-04T17:44:25.963+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-08-04T17:44:25.978+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-08-04T17:44:25.982+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=dbt_ipflow_dag, task_id=get_input_data, execution_date=20230803T000000, start_date=20230804T174425, end_date=20230804T174425
[2023-08-04T17:44:25.995+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 3 for task get_input_data (Bash command failed. The command returned a non-zero exit code 1.; 186)
[2023-08-04T17:44:26.030+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-08-04T17:44:26.050+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-08-04T18:01:43.505+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: dbt_ipflow_dag.get_input_data scheduled__2023-08-03T00:00:00+00:00 [queued]>
[2023-08-04T18:01:43.515+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: dbt_ipflow_dag.get_input_data scheduled__2023-08-03T00:00:00+00:00 [queued]>
[2023-08-04T18:01:43.517+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-08-04T18:01:43.518+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2023-08-04T18:01:43.519+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-08-04T18:01:43.529+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): get_input_data> on 2023-08-03 00:00:00+00:00
[2023-08-04T18:01:43.536+0000] {standard_task_runner.py:55} INFO - Started process 325 to run task
[2023-08-04T18:01:43.542+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dbt_ipflow_dag', 'get_input_data', 'scheduled__2023-08-03T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/dbt_ip_flow_dag.py', '--cfg-path', '/tmp/tmpn_a_xrhj']
[2023-08-04T18:01:43.546+0000] {standard_task_runner.py:83} INFO - Job 3: Subtask get_input_data
[2023-08-04T18:01:43.622+0000] {task_command.py:389} INFO - Running <TaskInstance: dbt_ipflow_dag.get_input_data scheduled__2023-08-03T00:00:00+00:00 [running]> on host ebb8780b02cb
[2023-08-04T18:01:43.690+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dbt_ipflow_dag
AIRFLOW_CTX_TASK_ID=get_input_data
AIRFLOW_CTX_EXECUTION_DATE=2023-08-03T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-08-03T00:00:00+00:00
[2023-08-04T18:01:43.698+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-08-04T18:01:43.700+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', "dbt run --select stg_ipflow_input_data --profiles-dir /opt/***/dbt/dbt_dsg_app --project-dir /opt/***/dbt/dbt_dsg_app  --target dev --vars '{'env': 'dev'}' "]
[2023-08-04T18:01:43.731+0000] {subprocess.py:86} INFO - Output:
[2023-08-04T18:01:43.770+0000] {subprocess.py:93} INFO - /bin/bash: line 1: dbt: command not found
[2023-08-04T18:01:43.771+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2023-08-04T18:01:43.785+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-08-04T18:01:43.790+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=dbt_ipflow_dag, task_id=get_input_data, execution_date=20230803T000000, start_date=20230804T180143, end_date=20230804T180143
[2023-08-04T18:01:43.801+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 3 for task get_input_data (Bash command failed. The command returned a non-zero exit code 127.; 325)
[2023-08-04T18:01:43.835+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-08-04T18:01:43.853+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-08-04T18:10:52.987+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: dbt_ipflow_dag.get_input_data scheduled__2023-08-03T00:00:00+00:00 [queued]>
[2023-08-04T18:10:53.000+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: dbt_ipflow_dag.get_input_data scheduled__2023-08-03T00:00:00+00:00 [queued]>
[2023-08-04T18:10:53.003+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-08-04T18:10:53.004+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2023-08-04T18:10:53.005+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-08-04T18:10:53.019+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): get_input_data> on 2023-08-03 00:00:00+00:00
[2023-08-04T18:10:53.030+0000] {standard_task_runner.py:55} INFO - Started process 137 to run task
[2023-08-04T18:10:53.037+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dbt_ipflow_dag', 'get_input_data', 'scheduled__2023-08-03T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/dbt_ip_flow_dag.py', '--cfg-path', '/tmp/tmptx5hlujy']
[2023-08-04T18:10:53.041+0000] {standard_task_runner.py:83} INFO - Job 3: Subtask get_input_data
[2023-08-04T18:10:53.147+0000] {task_command.py:389} INFO - Running <TaskInstance: dbt_ipflow_dag.get_input_data scheduled__2023-08-03T00:00:00+00:00 [running]> on host 2d3cfeb384b0
[2023-08-04T18:10:53.214+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dbt_ipflow_dag
AIRFLOW_CTX_TASK_ID=get_input_data
AIRFLOW_CTX_EXECUTION_DATE=2023-08-03T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-08-03T00:00:00+00:00
[2023-08-04T18:10:53.219+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-08-04T18:10:53.222+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', "dbt run --select stg_ipflow_input_data --profiles-dir /opt/***/dbt/dbt_dsg_app --project-dir /opt/***/dbt/dbt_dsg_app  --target dev --vars '{'env': 'dev'}' "]
[2023-08-04T18:10:53.239+0000] {subprocess.py:86} INFO - Output:
[2023-08-04T18:10:53.243+0000] {subprocess.py:93} INFO - /bin/bash: line 1: dbt: command not found
[2023-08-04T18:10:53.245+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2023-08-04T18:10:53.262+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-08-04T18:10:53.287+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=dbt_ipflow_dag, task_id=get_input_data, execution_date=20230803T000000, start_date=20230804T181052, end_date=20230804T181053
[2023-08-04T18:10:53.301+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 3 for task get_input_data (Bash command failed. The command returned a non-zero exit code 127.; 137)
[2023-08-04T18:10:53.329+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-08-04T18:10:53.356+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
