[2023-06-20T21:53:55.293+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: dbt_ipflow_dag.dbt_run_2 manual__2023-06-20T20:54:11.483592+00:00 [queued]>
[2023-06-20T21:53:55.332+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: dbt_ipflow_dag.dbt_run_2 manual__2023-06-20T20:54:11.483592+00:00 [queued]>
[2023-06-20T21:53:55.333+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-06-20T21:53:55.334+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2023-06-20T21:53:55.335+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-06-20T21:53:55.345+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): dbt_run_2> on 2023-06-20 20:54:11.483592+00:00
[2023-06-20T21:53:55.351+0000] {standard_task_runner.py:55} INFO - Started process 17344 to run task
[2023-06-20T21:53:55.357+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dbt_ipflow_dag', 'dbt_run_2', 'manual__2023-06-20T20:54:11.483592+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/dbt_ip_flow_dag.py', '--cfg-path', '/tmp/tmp4td3pzjg']
[2023-06-20T21:53:55.360+0000] {standard_task_runner.py:83} INFO - Job 21: Subtask dbt_run_2
[2023-06-20T21:53:55.427+0000] {task_command.py:389} INFO - Running <TaskInstance: dbt_ipflow_dag.dbt_run_2 manual__2023-06-20T20:54:11.483592+00:00 [running]> on host 635f1a4ac995
[2023-06-20T21:53:55.489+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dbt_ipflow_dag
AIRFLOW_CTX_TASK_ID=dbt_run_2
AIRFLOW_CTX_EXECUTION_DATE=2023-06-20T20:54:11.483592+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-06-20T20:54:11.483592+00:00
[2023-06-20T21:53:55.492+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-06-20T21:53:55.494+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'dbt debug']
[2023-06-20T21:53:55.516+0000] {subprocess.py:86} INFO - Output:
[2023-06-20T21:53:55.519+0000] {subprocess.py:93} INFO - /bin/bash: line 1: dbt: command not found
[2023-06-20T21:53:55.520+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2023-06-20T21:53:55.534+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-06-20T21:53:55.538+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=dbt_ipflow_dag, task_id=dbt_run_2, execution_date=20230620T205411, start_date=20230620T215355, end_date=20230620T215355
[2023-06-20T21:53:55.549+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 21 for task dbt_run_2 (Bash command failed. The command returned a non-zero exit code 127.; 17344)
[2023-06-20T21:53:55.569+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-06-20T21:53:55.588+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
