[2023-08-02T00:00:02.166+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: dbt_ipflow_dag.get_input_data scheduled__2023-08-01T00:00:00+00:00 [queued]>
[2023-08-02T00:00:02.173+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: dbt_ipflow_dag.get_input_data scheduled__2023-08-01T00:00:00+00:00 [queued]>
[2023-08-02T00:00:02.174+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-08-02T00:00:02.175+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2023-08-02T00:00:02.177+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-08-02T00:00:02.188+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): get_input_data> on 2023-08-01 00:00:00+00:00
[2023-08-02T00:00:02.196+0000] {standard_task_runner.py:55} INFO - Started process 39653 to run task
[2023-08-02T00:00:02.201+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dbt_ipflow_dag', 'get_input_data', 'scheduled__2023-08-01T00:00:00+00:00', '--job-id', '96', '--raw', '--subdir', 'DAGS_FOLDER/dbt_ip_flow_dag.py', '--cfg-path', '/tmp/tmpjyxq59zh']
[2023-08-02T00:00:02.204+0000] {standard_task_runner.py:83} INFO - Job 96: Subtask get_input_data
[2023-08-02T00:00:02.282+0000] {task_command.py:389} INFO - Running <TaskInstance: dbt_ipflow_dag.get_input_data scheduled__2023-08-01T00:00:00+00:00 [running]> on host 635f1a4ac995
[2023-08-02T00:00:02.347+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dbt_ipflow_dag
AIRFLOW_CTX_TASK_ID=get_input_data
AIRFLOW_CTX_EXECUTION_DATE=2023-08-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-08-01T00:00:00+00:00
[2023-08-02T00:00:02.351+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-08-02T00:00:02.353+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', "dbt run --select stg_ipflow_input_data --profiles-dir /opt/***/dbt/dbt_dsg_app --project-dir /opt/***/dbt/dbt_dsg_app  --target dev --vars '{'env': 'dev'}' "]
[2023-08-02T00:00:02.370+0000] {subprocess.py:86} INFO - Output:
[2023-08-02T00:00:03.805+0000] {subprocess.py:93} INFO - [0m00:00:03  Running with dbt=1.5.1
[2023-08-02T00:00:04.501+0000] {subprocess.py:93} INFO - [0m00:00:04  Found 12 models, 2 tests, 0 snapshots, 0 analyses, 321 macros, 0 operations, 0 seed files, 0 sources, 0 exposures, 0 metrics, 0 groups
[2023-08-02T00:00:04.507+0000] {subprocess.py:93} INFO - [0m00:00:04
[2023-08-02T00:00:05.000+0000] {subprocess.py:93} INFO - [0m00:00:04
[2023-08-02T00:00:05.002+0000] {subprocess.py:93} INFO - [0m00:00:05  Finished running  in 0 hours 0 minutes and 0.49 seconds (0.49s).
[2023-08-02T00:00:05.004+0000] {subprocess.py:93} INFO - [0m00:00:05  Encountered an error:
[2023-08-02T00:00:05.005+0000] {subprocess.py:93} INFO - Runtime Error
[2023-08-02T00:00:05.006+0000] {subprocess.py:93} INFO -   Database error while listing schemas in database "DEV_QA"
[2023-08-02T00:00:05.007+0000] {subprocess.py:93} INFO -   Database Error
[2023-08-02T00:00:05.009+0000] {subprocess.py:93} INFO -     250001 (08001): Failed to connect to DB: bcb55215.us-east-1.snowflakecomputing.com:443. Incorrect username or password was specified.
[2023-08-02T00:00:05.511+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-08-02T00:00:05.524+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-08-02T00:00:05.529+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=dbt_ipflow_dag, task_id=get_input_data, execution_date=20230801T000000, start_date=20230802T000002, end_date=20230802T000005
[2023-08-02T00:00:05.542+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 96 for task get_input_data (Bash command failed. The command returned a non-zero exit code 2.; 39653)
[2023-08-02T00:00:05.584+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-08-02T00:00:05.607+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
